/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.*;
import DAO.*;
import javax.swing.JOptionPane;

/**
 *
 * @author minht
 */
public class QuanLySach extends javax.swing.JFrame {
    Connection conn;
    List<Sach> listS = new ArrayList<>();
    DefaultTableModel tableModel = null;
    private String ISBNChose;
    boolean check = false;
    /**
     * Creates new form QuanLySach
     */
    public QuanLySach(String ISBN) {
        this.ISBNChose = ISBN;
        initComponents();
        
        setTitle("Quản lý Sách");
        setVisible(true);
        getContentPane().setBackground(new java.awt.Color(245,245,245));
        setLocationRelativeTo(null);

        
        inputGhiChu.setLineWrap(true);
        inputGhiChu.setWrapStyleWord(true);
        
        tableModel = (DefaultTableModel) table.getModel();
        table.setDefaultEditor(Object.class, null); 
        showData();
        cleanUI();
        
        btnSave.setVisible(false);
    }
    
       public void showData(){
         listS = SachDAO.getInstance().selectByCondition(ISBNChose);
         tableModel.setRowCount(0);
         listS.forEach((s) -> {
            tableModel.addRow(new Object[] {s.getISBN(), s.getMaSach(), s.getNamXB(),s.getGia(),s.getGhiChu()});
        });

    }
       
    public void cleanUI(){
        inputISBN.setText(ISBNChose);
        inputMaSach.setText("");
        inputGiaSach.setText("");
        inputNamXB.setText(" ");
        inputGhiChu.setText("");
        inputISBN.setEnabled(false);
        inputMaSach.setEnabled(false);
        inputGiaSach.setEnabled(false);
        inputNamXB.setEnabled(false);
        inputGhiChu.setEnabled(false);
        
        
        btnSave.setVisible(false);
        btnAdd.setText("Thêm");
        btnDel.setEnabled(true);
        btnUp.setEnabled(true);
        btnAdd.setEnabled(true);
    }
    
     public void defUI(){
        inputISBN.setText(ISBNChose);
        inputMaSach.setText("");
        inputGiaSach.setText("");
        inputNamXB.setText("");
        inputGhiChu.setText("");
        inputISBN.setEnabled(true);
        inputMaSach.setEnabled(true);
        inputGiaSach.setEnabled(true);
        inputNamXB.setEnabled(true);
        inputGhiChu.setEnabled(true);
    }
       
     private QuanLySach() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel10 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        choiceSearchMaS = new javax.swing.JRadioButton();
        choiceSearchNamXB = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        searchBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        inputSearch = new javax.swing.JTextPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        inputISBN = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        inputGiaSach = new javax.swing.JTextField();
        inputNamXB = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        inputGhiChu = new javax.swing.JTextArea();
        inputMaSach = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btnSave = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnUp = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        mainBtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        thoatBtn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuMain = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem8 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuDG = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        menuTheDG = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuQuanLyTT = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuQuanLyDauSach = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menuNhapSach = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        menuThemPN = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        menuNhaCC = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        menuQuanLyMuon = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        menuThemPhieuMuon = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuQuanLyPhieuTra = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        menuQuanLyThemPT = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        menuThongKe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel10.setBackground(new java.awt.Color(27, 70, 139));
        jPanel10.setPreferredSize(new java.awt.Dimension(0, 20));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(252, 252, 255));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(27, 70, 139));
        jLabel10.setText("TRƯỜNG ĐẠI HỌC TÀI CHÍNH MARKETING");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(27, 70, 139));
        jLabel11.setText("THƯ VIỆN");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(27, 70, 139));
        jPanel6.setPreferredSize(new java.awt.Dimension(0, 20));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));
        jPanel1.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(70, 67));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thuvien/img/miniLogo.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(27, 70, 139));
        jLabel8.setText("DANH SÁCH SÁCH");

        jPanel2.setBackground(new java.awt.Color(245, 245, 245));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "Tìm kiếm sách", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        jPanel3.setBackground(new java.awt.Color(245, 245, 245));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "Tìm theo", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        buttonGroup1.add(choiceSearchMaS);
        choiceSearchMaS.setText("Mã Sách");
        choiceSearchMaS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choiceSearchMaSActionPerformed(evt);
            }
        });

        buttonGroup1.add(choiceSearchNamXB);
        choiceSearchNamXB.setText("Năm Xuất Bản");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(choiceSearchMaS)
                .addGap(18, 18, 18)
                .addComponent(choiceSearchNamXB)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(choiceSearchMaS)
                    .addComponent(choiceSearchNamXB))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(245, 245, 245));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "Nhập thông tin cần tìm", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        searchBtn.setText("Tìm Kiếm");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(inputSearch);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(searchBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(245, 245, 245));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "Thông tin sách", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        jLabel2.setText("ISBN :");

        jLabel3.setText("Năm Xuất Bản :");

        jLabel4.setText("Giá Sách :");

        jLabel5.setText("Mã Sách");

        jLabel9.setText("Ghi Chú :");

        inputGhiChu.setColumns(20);
        inputGhiChu.setRows(5);
        jScrollPane2.setViewportView(inputGhiChu);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2))
                .addGap(12, 12, 12)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(inputGiaSach, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputISBN)
                    .addComponent(inputMaSach, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputNamXB, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(inputNamXB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(inputISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(inputMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(inputGiaSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16))))
        );

        jPanel8.setBackground(new java.awt.Color(245, 245, 245));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "Danh sách", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ISBN", "Mã Sách", "Năm Xuất Bản", "Giá", "Ghi Chú"
            }
        ));
        table.setRowHeight(30);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        btnSave.setText("Lưu");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnAdd.setText("Thêm");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUp.setText("Sửa");
        btnUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpActionPerformed(evt);
            }
        });

        btnDel.setText("Xóa");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        mainBtn.setText("Trang chủ");
        mainBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainBtnActionPerformed(evt);
            }
        });

        jButton2.setText("Quản lý đầu sách");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        thoatBtn.setText("Thoát");
        thoatBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thoatBtnActionPerformed(evt);
            }
        });

        jMenuBar1.setBackground(new java.awt.Color(204, 204, 204));
        jMenuBar1.setOpaque(true);

        jMenu1.setText("Tiện ích");
        jMenu1.setMargin(new java.awt.Insets(3, 8, 3, 8));

        menuMain.setText("Trang chủ");
        menuMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMainActionPerformed(evt);
            }
        });
        jMenu1.add(menuMain);
        jMenu1.add(jSeparator2);

        jMenuItem8.setText("Giới thiệu");
        jMenu1.add(jMenuItem8);
        jMenu1.add(jSeparator3);

        jMenuItem9.setText("Thông tin liên hệ");
        jMenu1.add(jMenuItem9);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Quản lý độc giả");
        jMenu2.setMargin(new java.awt.Insets(3, 8, 3, 8));

        menuDG.setText("Danh sách độc giả");
        menuDG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDGActionPerformed(evt);
            }
        });
        jMenu2.add(menuDG);
        jMenu2.add(jSeparator4);

        menuTheDG.setText("Danh sách thẻ độc giả");
        menuTheDG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTheDGActionPerformed(evt);
            }
        });
        jMenu2.add(menuTheDG);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Quản lý thu thư");
        jMenu3.setMargin(new java.awt.Insets(3, 8, 3, 8));

        menuQuanLyTT.setText("Danh mục thủ thư");
        menuQuanLyTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuQuanLyTTActionPerformed(evt);
            }
        });
        jMenu3.add(menuQuanLyTT);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Quản lý sách");
        jMenu4.setMargin(new java.awt.Insets(3, 8, 3, 8));

        menuQuanLyDauSach.setText("Danh mục đầu sách");
        menuQuanLyDauSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuQuanLyDauSachActionPerformed(evt);
            }
        });
        jMenu4.add(menuQuanLyDauSach);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Quản lý nhập sách");
        jMenu5.setMargin(new java.awt.Insets(3, 8, 3, 8));

        menuNhapSach.setText("Danh mục nhập sách");
        menuNhapSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNhapSachActionPerformed(evt);
            }
        });
        jMenu5.add(menuNhapSach);
        jMenu5.add(jSeparator6);

        menuThemPN.setText("Thêm Phiếu nhập");
        menuThemPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuThemPNActionPerformed(evt);
            }
        });
        jMenu5.add(menuThemPN);
        jMenu5.add(jSeparator5);

        menuNhaCC.setText("Danh mục nhà cung cấp");
        menuNhaCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNhaCCActionPerformed(evt);
            }
        });
        jMenu5.add(menuNhaCC);

        jMenuBar1.add(jMenu5);

        jMenu7.setText("Quản lý mượn - trả");
        jMenu7.setMargin(new java.awt.Insets(3, 8, 3, 8));

        menuQuanLyMuon.setText("Danh sách mượn");
        menuQuanLyMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuQuanLyMuonActionPerformed(evt);
            }
        });
        jMenu7.add(menuQuanLyMuon);
        jMenu7.add(jSeparator7);

        menuThemPhieuMuon.setText("Thêm phiếu mượn");
        menuThemPhieuMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuThemPhieuMuonActionPerformed(evt);
            }
        });
        jMenu7.add(menuThemPhieuMuon);
        jMenu7.add(jSeparator1);

        menuQuanLyPhieuTra.setText("Danh sách trả");
        menuQuanLyPhieuTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuQuanLyPhieuTraActionPerformed(evt);
            }
        });
        jMenu7.add(menuQuanLyPhieuTra);
        jMenu7.add(jSeparator8);

        menuQuanLyThemPT.setText("Thêm phiếu trả");
        menuQuanLyThemPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuQuanLyThemPTActionPerformed(evt);
            }
        });
        jMenu7.add(menuQuanLyThemPT);

        jMenuBar1.add(jMenu7);

        jMenu8.setText("Tổng thống kê");
        jMenu8.setMargin(new java.awt.Insets(3, 8, 3, 8));

        menuThongKe.setText("Thống kê");
        menuThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuThongKeActionPerformed(evt);
            }
        });
        jMenu8.add(menuThongKe);

        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 711, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 711, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSave)
                        .addGap(16, 16, 16)
                        .addComponent(btnAdd)
                        .addGap(16, 16, 16)
                        .addComponent(btnUp)
                        .addGap(16, 16, 16)
                        .addComponent(btnDel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(mainBtn)
                        .addGap(15, 15, 15)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(thoatBtn))
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnUp)
                    .addComponent(btnDel)
                    .addComponent(btnSave))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainBtn)
                    .addComponent(jButton2)
                    .addComponent(thoatBtn))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void choiceSearchMaSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choiceSearchMaSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_choiceSearchMaSActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        if(choiceSearchMaS.isSelected()){
            String search = inputSearch.getText();
            listS = SachDAO.getInstance().selectByCondition(search,"", 1);
            tableModel.setRowCount(0);
            listS.forEach((s) -> {
                tableModel.addRow(new Object[] {s.getISBN(), s.getMaSach(), s.getNamXB(),s.getGia(),s.getGhiChu()});

            });
        }
        else if(choiceSearchNamXB.isSelected()){
            String search = inputSearch.getText();
            listS = SachDAO.getInstance().selectByCondition(search,ISBNChose, 2);
            tableModel.setRowCount(0);
            listS.forEach((s) -> {
                tableModel.addRow(new Object[] {s.getISBN(), s.getMaSach(), s.getNamXB(),s.getGia(),s.getGhiChu()});

            });
        }
        else {
           JOptionPane.showMessageDialog(null, "Vui lòng chọn Hình Thức Bạn Muốn Tìm Theo");
            showData(); 
        }

//
        if (table.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Không có dữ liệu");
            showData();
        }
        buttonGroup1.clearSelection();
        inputSearch.setText("");
    }//GEN-LAST:event_searchBtnActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:

        String tblMaSach = tableModel.getValueAt(table.getSelectedRow(), 1).toString();
        String tblNamXB = tableModel.getValueAt(table.getSelectedRow(), 2).toString();
        String tblGia = tableModel.getValueAt(table.getSelectedRow(), 3).toString();
        String tblGhiChu = tableModel.getValueAt(table.getSelectedRow(), 4).toString();




        inputMaSach.setText(tblMaSach);
        inputNamXB.setText(tblNamXB);
        inputGiaSach.setText(tblGia);
        inputGhiChu.setText(tblGhiChu);

    }//GEN-LAST:event_tableMouseClicked

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        if(check) {
            
                String msSach = "";
                String splitMaSach ="";
                int newMaSachInt;
                String newMaSachString ="";
                ArrayList<Sach> listNewMaSach = SachDAO.getInstance().selectNewMaSach();
                for (Sach s : listNewMaSach) {
                    msSach = s.getMaSach();
                }
                splitMaSach = msSach.substring(1);
                newMaSachInt = Integer.valueOf(splitMaSach) +1;
                if (newMaSachInt < 10) {
                   newMaSachString = "S000" + Integer.toString(newMaSachInt);
                } else if (newMaSachInt > 10) {
                   newMaSachString = "S00" + Integer.toString(newMaSachInt);
                }
                System.out.println(newMaSachString);
            //                inputMa.setEnabled(true);
            int NamXB = Integer.parseInt(inputNamXB.getText());
            String Gia = inputGiaSach.getText();
            String GhiChu = inputGhiChu.getText();
            Sach s = new Sach(newMaSachString,ISBNChose,Integer.parseInt(Gia),NamXB,GhiChu);

            try {
                SachDAO.getInstance().insert(s);
                JOptionPane.showMessageDialog(null, "Thêm Sách thành công");
                showData();
                btnAdd.setText("Thêm");
                cleanUI();
            } catch (Exception e) {
                e.printStackTrace();
            }
            
            //
        }
        //
        else {
            String MaSach = inputMaSach.getText();
            String NamXB = inputNamXB.getText();
            String Gia = inputGiaSach.getText();
            String GhiChu = inputGhiChu.getText();
            Sach s = new Sach(MaSach,ISBNChose,Integer.parseInt(Gia),Integer.parseInt(NamXB),GhiChu);

            try {
                SachDAO.getInstance().update(s);
                JOptionPane.showMessageDialog(null, "Sửa Sách thành công");
                showData();
                btnUp.setText("Sửa");
                cleanUI();

            } catch (Exception ex) {
                ex.printStackTrace();

            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        defUI();
        if (btnAdd.getText().equalsIgnoreCase("Thêm")) {
            defUI();
            inputISBN.setEnabled(false);
            inputMaSach.setEnabled(false);
            btnAdd.setText("Hủy");
            btnDel.setEnabled(false);
            btnUp.setEnabled(false);
            btnSave.setVisible(true);
            check = true;
        } else {
            cleanUI();
            btnAdd.setText("Thêm");
            btnDel.setEnabled(true);
            btnUp.setEnabled(true);
            JOptionPane.showMessageDialog(null, "Hủy thêm Sách thành công");
        }

    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpActionPerformed
        // TODO add your handling code here:
        if (btnUp.getText().equalsIgnoreCase("Sửa")) {
            if(table.getSelectedRowCount() != 1) {
                JOptionPane.showMessageDialog(null, "Vui lòng chọn hàng muốn sửa");
            }
            else {
               inputISBN.setEnabled(false);
                btnUp.setText("Hủy");
                btnAdd.setEnabled(false);
                btnDel.setEnabled(false);
                btnSave.setEnabled(true);
                inputISBN.setEnabled(false);
                inputMaSach.setEnabled(true);
                inputGiaSach.setEnabled(true);
                inputNamXB.setEnabled(true);
                inputGhiChu.setEnabled(true);
                btnSave.setVisible(true);
                check = false;
            }
        }
        else {
            cleanUI();
            btnUp.setText("Sửa");
            JOptionPane.showMessageDialog(null, "Hủy sửa Sách thành công");
        }
    }//GEN-LAST:event_btnUpActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        // TODO add your handling code here:
        if(table.getSelectedRowCount() != 1) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn hàng muốn Xóa");
        }
        else {
            String MaSach = inputMaSach.getText();
            String NamXB = inputNamXB.getText();
            String Gia = inputGiaSach.getText();
            String GhiChu = inputGhiChu.getText();
            Sach s = new Sach(MaSach,ISBNChose,Integer.parseInt(Gia),Integer.parseInt(NamXB),GhiChu);

            try {
                SachDAO.getInstance().delete(s);
                JOptionPane.showMessageDialog(null, "Xóa Sách thành công");
                showData();
                cleanUI();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnDelActionPerformed

    private void mainBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainBtnActionPerformed
        // TODO add your handling code here:
        Main main = new Main();
        setVisible(false);
    }//GEN-LAST:event_mainBtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        QuanLyDauSach mainDauSach = new QuanLyDauSach();
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void thoatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thoatBtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_thoatBtnActionPerformed

    private void menuMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMainActionPerformed
        // TODO add your handling code here:
        Main main = new Main();
        setVisible(false);
    }//GEN-LAST:event_menuMainActionPerformed

    private void menuDGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDGActionPerformed
        // TODO add your handling code here:
        QuanLyDG mainDG = new QuanLyDG();
        setVisible(false);
    }//GEN-LAST:event_menuDGActionPerformed

    private void menuTheDGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTheDGActionPerformed
        // TODO add your handling code here:
        QuanLyThe mainThe = new QuanLyThe();
        setVisible(false);
    }//GEN-LAST:event_menuTheDGActionPerformed

    private void menuQuanLyTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuQuanLyTTActionPerformed
        // TODO add your handling code here:
        QuanLyThuThu mainTT = new QuanLyThuThu();
        setVisible(false);
    }//GEN-LAST:event_menuQuanLyTTActionPerformed

    private void menuQuanLyDauSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuQuanLyDauSachActionPerformed
        // TODO add your handling code here:
        QuanLyDauSach mainQuanLyDauSach = new QuanLyDauSach();
        setVisible(false);
    }//GEN-LAST:event_menuQuanLyDauSachActionPerformed

    private void menuNhapSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNhapSachActionPerformed
        // TODO add your handling code here:
        QuanLyPhieuNhap mainLyPhieuNhap = new QuanLyPhieuNhap();
        setVisible(false);
    }//GEN-LAST:event_menuNhapSachActionPerformed

    private void menuThemPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuThemPNActionPerformed
        // TODO add your handling code here:
        QuanLyThemPN menQuanLyThemPN = new QuanLyThemPN();
        setVisible(false);
    }//GEN-LAST:event_menuThemPNActionPerformed

    private void menuNhaCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNhaCCActionPerformed
        // TODO add your handling code here:
        QuanLyNhaCungCap mainNCC = new QuanLyNhaCungCap();
        setVisible(false);
    }//GEN-LAST:event_menuNhaCCActionPerformed

    private void menuQuanLyMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuQuanLyMuonActionPerformed
        // TODO add your handling code here:
        QuanLyMuon mainMuon = new QuanLyMuon();
        setVisible(false);
    }//GEN-LAST:event_menuQuanLyMuonActionPerformed

    private void menuThemPhieuMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuThemPhieuMuonActionPerformed
        // TODO add your handling code here:
        QuanLyThemPM mainThemPM = new QuanLyThemPM();
        setVisible(false);
    }//GEN-LAST:event_menuThemPhieuMuonActionPerformed

    private void menuQuanLyPhieuTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuQuanLyPhieuTraActionPerformed
        // TODO add your handling code here:
        QuanLyPhieuTra mainQuanLyPhieuTra = new QuanLyPhieuTra();
        setVisible(false);
    }//GEN-LAST:event_menuQuanLyPhieuTraActionPerformed

    private void menuQuanLyThemPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuQuanLyThemPTActionPerformed
        // TODO add your handling code here:
        QuanLyThemPT mainThemPT = new QuanLyThemPT();
        setVisible(false);
    }//GEN-LAST:event_menuQuanLyThemPTActionPerformed

    private void menuThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuThongKeActionPerformed
        // TODO add your handling code here:
        ThongKe mainTk = new ThongKe();
        setVisible(false);
    }//GEN-LAST:event_menuThongKeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLySach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLySach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLySach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLySach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLySach().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUp;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton choiceSearchMaS;
    private javax.swing.JRadioButton choiceSearchNamXB;
    private javax.swing.JTextArea inputGhiChu;
    private javax.swing.JTextField inputGiaSach;
    private javax.swing.JTextField inputISBN;
    private javax.swing.JTextField inputMaSach;
    private javax.swing.JTextField inputNamXB;
    private javax.swing.JTextPane inputSearch;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JButton mainBtn;
    private javax.swing.JMenuItem menuDG;
    private javax.swing.JMenuItem menuMain;
    private javax.swing.JMenuItem menuNhaCC;
    private javax.swing.JMenuItem menuNhapSach;
    private javax.swing.JMenuItem menuQuanLyDauSach;
    private javax.swing.JMenuItem menuQuanLyMuon;
    private javax.swing.JMenuItem menuQuanLyPhieuTra;
    private javax.swing.JMenuItem menuQuanLyTT;
    private javax.swing.JMenuItem menuQuanLyThemPT;
    private javax.swing.JMenuItem menuTheDG;
    private javax.swing.JMenuItem menuThemPN;
    private javax.swing.JMenuItem menuThemPhieuMuon;
    private javax.swing.JMenuItem menuThongKe;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTable table;
    private javax.swing.JButton thoatBtn;
    // End of variables declaration//GEN-END:variables
}
