/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import DAO.CTPhieuTraDAO;
import DAO.DauSachDAO;
import DAO.LoaiVPDAO;
import DAO.PhieuMuonDAO;
import DAO.PhieuMuonToHopDAO;
import DAO.PhieuTraDAO;
import DAO.SachDAO;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.CTPhieuTra;
import model.DauSach;
import model.LoaiVP;
import model.PhieuMuon;
import model.PhieuMuonToHop;
import model.PhieuTra;
import model.Sach;

/**
 *
 * @author minht
 */
public class QuanLyThemPT extends javax.swing.JFrame {
    public String choiceTenDG = "";
    public String choiceVP = "";
    public String tenDS = "";
    public String MaSach = "";
    public long Phat = 0;
    
    Connection conn;
    DefaultTableModel tableModel = null;
    
    /**
     * Creates new form QuanLyThemPT
     */
    public QuanLyThemPT() {
        initComponents();
        setTitle("Quản lý thêm phiếu trả");
        setVisible(true);
        setLocationRelativeTo(null);
        setResizable(false);
        getContentPane().setBackground(new java.awt.Color(245,245,245));

        
        addListName();
        addListVP();
        
        txtTreHan.setVisible(false);
        expectBtn.setVisible(false);
        valueTH.setVisible(false);
        plusBtn.setVisible(false);
        
       saveBtn.setVisible(false);

        
    }
    
    public void addListName(){
        choiceListName.add("");
        ArrayList<PhieuMuonToHop> listMM = PhieuMuonToHopDAO.getInstance().selectNameDGNotInPT();
        Set<PhieuMuonToHop> uniqueResults = new HashSet<>(listMM);
        for (PhieuMuonToHop pm : listMM) {
            choiceListName.add(pm.getHoTen());
        }
    }
    
    public void addListSach(){
        listSach.add("");
        ArrayList<DauSach> listS = DauSachDAO.getInstance().selectTenSachNotInPT(choiceTenDG,1);{
        for (DauSach dauSach : listS) {
            listSach.add(dauSach.getTenSach());
            }
           
        }

        if (listSach.getItemCount() == 1) {
          ArrayList<DauSach> listS1 = DauSachDAO.getInstance().selectTenSachNotInPT(choiceTenDG,2);{
        for (DauSach dauSach : listS1) {
            listSach.add(dauSach.getTenSach());
            }
           
        }  
        }
    }
    
    public void addListVP(){
        choiceListVP.add("");
        ArrayList<LoaiVP> listVp = LoaiVPDAO.getInstance().selectTenViPham();
        for (LoaiVP loaiVP : listVp) {
            choiceListVP.add(loaiVP.getTenLoaiVP());
        }
    }
    
    
        public void defUI(){
        listSach.select(0);
        choiceListVP.select(0);
        valueTH.setText("0");
        txtTreHan.setVisible(false);
        expectBtn.setVisible(false);
        valueTH.setVisible(false);
        plusBtn.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        addPMBTN = new javax.swing.JButton();
        inputNgayTra = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        addBtn = new javax.swing.JButton();
        upBtn = new javax.swing.JButton();
        delBTN = new javax.swing.JButton();
        listSach = new java.awt.Choice();
        jLabel8 = new javax.swing.JLabel();
        choiceListVP = new java.awt.Choice();
        saveBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        choiceListName = new java.awt.Choice();
        txtTreHan = new javax.swing.JLabel();
        expectBtn = new javax.swing.JButton();
        valueTH = new javax.swing.JLabel();
        plusBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listTableAdd = new javax.swing.JTable();
        mainBtn = new javax.swing.JButton();
        thoatBtn = new javax.swing.JButton();
        mainPT = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuMain = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem8 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuDG = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        menuTheDG = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuQuanLyTT = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuQuanLyDauSach = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menuNhapSach = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        menuThemPN = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        menuNhaCC = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        menuQuanLyMuon = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        menuThemPhieuMuon = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuQuanLyPhieuTra = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        menuQuanLyThemPT = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        menuThongKe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(27, 70, 139));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(252, 252, 255));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(27, 70, 139));
        jLabel10.setText("TRƯỜNG ĐẠI HỌC TÀI CHÍNH MARKETING");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(27, 70, 139));
        jLabel11.setText("THƯ VIỆN");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(0, 659, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(70, 67));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thuvien/img/miniLogo.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        jPanel6.setBackground(new java.awt.Color(27, 70, 139));
        jPanel6.setPreferredSize(new java.awt.Dimension(0, 20));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jLabel6.setBackground(new java.awt.Color(27, 70, 139));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(27, 70, 139));
        jLabel6.setText("THÊM PHIẾU TRẢ");

        jPanel2.setBackground(new java.awt.Color(245, 245, 245));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "Tạo Phiếu Trả", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        jLabel4.setText("Ngày Trả");

        addPMBTN.setText("Lưu");
        addPMBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPMBTNActionPerformed(evt);
            }
        });

        inputNgayTra.setDateFormatString("dd-MM-yyyy");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGap(103, 103, 103)
                            .addComponent(addPMBTN))
                        .addComponent(inputNgayTra, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel4))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputNgayTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addPMBTN)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(245, 245, 245));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "Mặt Hàng Muốn Trả"));

        jLabel7.setText("Chọn Sách Muốn Trả :");

        addBtn.setText("Thêm");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        upBtn.setText("Sửa");
        upBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upBtnActionPerformed(evt);
            }
        });

        delBTN.setText("Xóa");
        delBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBTNActionPerformed(evt);
            }
        });

        listSach.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                listSachItemStateChanged(evt);
            }
        });

        jLabel8.setText("Kiểm tra vi phạm :");

        choiceListVP.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                choiceListVPItemStateChanged(evt);
            }
        });

        saveBtn.setText("Lưu");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Chọn Người Mượn :");

        choiceListName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                choiceListNameItemStateChanged(evt);
            }
        });

        txtTreHan.setText("Số Ngày Trễ :");

        expectBtn.setText("-");
        expectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expectBtnActionPerformed(evt);
            }
        });

        valueTH.setText("0");
        valueTH.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                valueTHPropertyChange(evt);
            }
        });

        plusBtn.setText("+");
        plusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(txtTreHan))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(expectBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(valueTH)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(plusBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addBtn)
                        .addGap(18, 18, 18)
                        .addComponent(upBtn)
                        .addGap(18, 18, 18)
                        .addComponent(delBTN)
                        .addGap(18, 18, 18)
                        .addComponent(saveBtn)
                        .addGap(27, 27, 27))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(listSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(78, 78, 78))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(choiceListName, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(choiceListVP, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(choiceListName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(listSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(choiceListVP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(upBtn)
                            .addComponent(delBTN)
                            .addComponent(saveBtn)
                            .addComponent(addBtn)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTreHan)
                            .addComponent(expectBtn)
                            .addComponent(valueTH)
                            .addComponent(plusBtn))))
                .addGap(24, 24, 24))
        );

        listTableAdd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Sách", "Tên Sách", "Vi Phạm", "Phạt"
            }
        ));
        listTableAdd.setRowHeight(30);
        jScrollPane1.setViewportView(listTableAdd);

        mainBtn.setText("Trang chủ");
        mainBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainBtnActionPerformed(evt);
            }
        });

        thoatBtn.setText("Thoát");
        thoatBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thoatBtnActionPerformed(evt);
            }
        });

        mainPT.setText("Quản lý phiếu trả");
        mainPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainPTActionPerformed(evt);
            }
        });

        jMenuBar1.setBackground(new java.awt.Color(204, 204, 204));
        jMenuBar1.setOpaque(true);

        jMenu1.setText("Tiện ích");
        jMenu1.setMargin(new java.awt.Insets(3, 12, 3, 12));

        menuMain.setText("Trang chủ");
        menuMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMainActionPerformed(evt);
            }
        });
        jMenu1.add(menuMain);
        jMenu1.add(jSeparator2);

        jMenuItem8.setText("Giới thiệu");
        jMenu1.add(jMenuItem8);
        jMenu1.add(jSeparator3);

        jMenuItem9.setText("Thông tin liên hệ");
        jMenu1.add(jMenuItem9);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Quản lý độc giả");
        jMenu2.setMargin(new java.awt.Insets(3, 12, 3, 12));

        menuDG.setText("Danh sách độc giả");
        menuDG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDGActionPerformed(evt);
            }
        });
        jMenu2.add(menuDG);
        jMenu2.add(jSeparator4);

        menuTheDG.setText("Danh sách thẻ độc giả");
        menuTheDG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTheDGActionPerformed(evt);
            }
        });
        jMenu2.add(menuTheDG);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Quản lý thu thư");
        jMenu3.setMargin(new java.awt.Insets(3, 12, 3, 12));

        menuQuanLyTT.setText("Danh mục thủ thư");
        menuQuanLyTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuQuanLyTTActionPerformed(evt);
            }
        });
        jMenu3.add(menuQuanLyTT);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Quản lý sách");
        jMenu4.setMargin(new java.awt.Insets(3, 12, 3, 12));

        menuQuanLyDauSach.setText("Danh mục đầu sách");
        menuQuanLyDauSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuQuanLyDauSachActionPerformed(evt);
            }
        });
        jMenu4.add(menuQuanLyDauSach);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Quản lý nhập sách");
        jMenu5.setMargin(new java.awt.Insets(3, 12, 3, 12));

        menuNhapSach.setText("Danh mục nhập sách");
        menuNhapSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNhapSachActionPerformed(evt);
            }
        });
        jMenu5.add(menuNhapSach);
        jMenu5.add(jSeparator6);

        menuThemPN.setText("Thêm Phiếu nhập");
        menuThemPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuThemPNActionPerformed(evt);
            }
        });
        jMenu5.add(menuThemPN);
        jMenu5.add(jSeparator5);

        menuNhaCC.setText("Danh mục nhà cung cấp");
        menuNhaCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNhaCCActionPerformed(evt);
            }
        });
        jMenu5.add(menuNhaCC);

        jMenuBar1.add(jMenu5);

        jMenu7.setText("Quản lý mượn - trả");
        jMenu7.setMargin(new java.awt.Insets(3, 12, 3, 12));

        menuQuanLyMuon.setText("Danh sách mượn");
        menuQuanLyMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuQuanLyMuonActionPerformed(evt);
            }
        });
        jMenu7.add(menuQuanLyMuon);
        jMenu7.add(jSeparator7);

        menuThemPhieuMuon.setText("Thêm phiếu mượn");
        menuThemPhieuMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuThemPhieuMuonActionPerformed(evt);
            }
        });
        jMenu7.add(menuThemPhieuMuon);
        jMenu7.add(jSeparator1);

        menuQuanLyPhieuTra.setText("Danh sách trả");
        menuQuanLyPhieuTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuQuanLyPhieuTraActionPerformed(evt);
            }
        });
        jMenu7.add(menuQuanLyPhieuTra);
        jMenu7.add(jSeparator8);

        menuQuanLyThemPT.setText("Thêm phiếu trả");
        menuQuanLyThemPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuQuanLyThemPTActionPerformed(evt);
            }
        });
        jMenu7.add(menuQuanLyThemPT);

        jMenuBar1.add(jMenu7);

        jMenu8.setText("Tổng thống kê");
        jMenu8.setMargin(new java.awt.Insets(3, 12, 3, 12));

        menuThongKe.setText("Thống kê");
        menuThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuThongKeActionPerformed(evt);
            }
        });
        jMenu8.add(menuThongKe);

        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 1055, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(mainBtn)
                        .addGap(18, 18, 18)
                        .addComponent(mainPT)
                        .addGap(10, 10, 10)
                        .addComponent(thoatBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 818, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(thoatBtn)
                    .addComponent(mainBtn)
                    .addComponent(mainPT))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addPMBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPMBTNActionPerformed
        // TODO add your handling code here:
        String msPT = "";
        String splitMT ="";
        int newMaPTInt;
        String newMaTString ="";
        ArrayList<PhieuTra> listNewPT = PhieuTraDAO.getInstance().selectMaT();
        for (PhieuTra pt : listNewPT) {
            msPT = pt.getMaT();
        }
        splitMT = msPT.substring(2);
        newMaPTInt = Integer.valueOf(splitMT) +1;
        if (newMaPTInt < 10) {
            newMaTString = "PT00" + Integer.toString(newMaPTInt);
        } else if (newMaPTInt > 10) {
            newMaTString = "PT0" + Integer.toString(newMaPTInt);
        }

        System.out.println(newMaTString);
//          
        String MaM = "";
        ArrayList<PhieuMuonToHop> listMaM = PhieuMuonToHopDAO.getInstance().selectMaMNotInPT(choiceTenDG,1,MaSach);
        for (PhieuMuonToHop pm : listMaM) {
            MaM = pm.getMaM();
        }
        if(MaM.equalsIgnoreCase("")){
        ArrayList<PhieuMuonToHop> listMaM2 = PhieuMuonToHopDAO.getInstance().selectMaMNotInPT(choiceTenDG,2,MaSach);
        for (PhieuMuonToHop pm : listMaM2) {
            MaM = pm.getMaM();
        } 
        }
        System.out.println(MaM);

//        //
//        //
//        String MaDG = inputMaDG.getText();
//        String MaTT = inputMaTT.getText();
//
        Calendar date1 = inputNgayTra.getCalendar();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String NgayTra = dateFormat.format(date1.getTime());
        System.out.println(NgayTra);
//
//        Calendar date2 = inputNgayHH.getCalendar();
//        SimpleDateFormat dateFormat2 = new SimpleDateFormat("yyyy-MM-dd");
//        String NgayHH = dateFormat2.format(date2.getTime());
//        System.out.println(NgayHH);
//
//        int SoLuongM = tableModel.getRowCount();
//        System.out.println(SoLuongM);
//
//        if(listGhiChu.getItem(listGhiChu.getSelectedIndex()).equalsIgnoreCase("Mượn về nhà")) {
//            GhiChu = "Mượn về nhà";
//        }else {
//            GhiChu = "Mượn đọc tại chỗ";
//        }

        int SoLuong = 0;
        ArrayList<PhieuMuon> listPM = PhieuMuonDAO.getInstance().selectSoLuongMNotInPT(MaM);
        for (PhieuMuon phieuMuon : listPM) {
            SoLuong = phieuMuon.getSoLuongMuon();
        }
        System.out.println(SoLuong);
        
        
        int SoLuongT = listTableAdd.getRowCount();
        System.out.println(SoLuongT);
       

        PhieuTra pt = new PhieuTra(newMaTString, MaM, NgayTra, SoLuong, SoLuongT);
        try {
            PhieuTraDAO.getInstance().insert(pt);
            JOptionPane.showMessageDialog(null, "Thêm phiếu trả thành công");
            inputNgayTra.setDate(null);
        } catch (Exception ex) {
            ex.printStackTrace();

        }
        SoLuong = SoLuong - 1;
////        //
        int rowCount = listTableAdd.getRowCount();
        int columnCount = listTableAdd.getColumnCount();
        String MaSach = "";
        String MaVP = "";
        int Phat = 0;

        for (int rowIndex = 0; rowIndex < rowCount; rowIndex++) {
            for (int columnIndex = 0; columnIndex < columnCount; columnIndex++) {
                Object value = listTableAdd.getValueAt(rowIndex, columnIndex);
                if (columnIndex == 0) {
                    MaSach = (String) value;
                }
                if (columnIndex == 2) {
                    String VP = (String) value;
                    if(VP.equalsIgnoreCase("Không vi phạm")) {
                        MaVP = "VP000";
                    }else if(VP.equalsIgnoreCase("Mất tài liệu")){
                        MaVP = "VP001";
                    } else if(VP.equalsIgnoreCase("Tài liệu bị xé hoặc rách 1/3 trở lên")){
                        MaVP = "VP002";
                    } else if(VP.equalsIgnoreCase("Tài liệu bị xé hoặc rách 1/3 trở lên")){
                        MaVP = "VP003";
                    } else if (VP.equalsIgnoreCase("Tài liệu bị bẩn, nhàu nát (ghi chép, gạch xóa, tô đậm)")){
                        MaVP = "VP004";
                    }else {
                        MaVP = "VP005";
                    }
                }
                if (columnIndex == 3) {
                    if(value instanceof  Integer){
                        Phat = (int)value;
                    } else if(value instanceof  String){
                        Phat = Integer.valueOf((String) value);
                    }
                }

            }


            
            
            CTPhieuTra ctpn = new CTPhieuTra(newMaTString,MaM,MaSach,MaVP,Phat);
            try {
                CTPhieuTraDAO.getInstance().insert(ctpn);
            } catch (Exception ex) {
                ex.printStackTrace();

            }
        }
        tableModel.setRowCount(0);
        choiceListName.select(0);
        listSach.select(0);
        choiceListName.setEnabled(true);
        choiceListName.removeAll();
        addListName();
    }//GEN-LAST:event_addPMBTNActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        MaSach = "";
        ArrayList<CTPhieuTra> listPT = CTPhieuTraDAO.getInstance().selectMaSachNotInPT(choiceTenDG, tenDS,1);
        for (CTPhieuTra pt : listPT) {
            MaSach = pt.getMaSach();
        }
        System.out.println(MaSach);
        System.out.println(choiceTenDG);
        System.out.println(tenDS);
        if (MaSach.equalsIgnoreCase("")) {
          ArrayList<CTPhieuTra> listPT2 = CTPhieuTraDAO.getInstance().selectMaSachNotInPT(choiceTenDG, tenDS,2);
        for (CTPhieuTra pt : listPT2) {
            MaSach = pt.getMaSach();
        }  
        }
        
        int Gia = 0;
        ArrayList<Sach> listSach = SachDAO.getInstance().selectByConditionGia(MaSach, "", 2);
        for (Sach sach : listSach) {
            Gia = sach.getGia();
        }
//        System.out.println(Gia);
        
        if(choiceVP.equalsIgnoreCase("Không vi phạm")){
            Phat= 0;
        }else if (choiceVP.equalsIgnoreCase("Mất tài liệu")) {
            Phat = Gia*3;
        } else if (choiceVP.equalsIgnoreCase("Tài liệu bị xé hoặc rách 1/3 trở lên")) {
            Phat = Gia*2;
        } else if (choiceVP.equalsIgnoreCase("Tài liệu bị bẩn, nhàu nát (ghi chép, gạch xóa, tô đậm)")) {
            Phat = Gia;
        } else if (choiceVP.equalsIgnoreCase("Trả tài liệu trễ hạn (tài liệu mượn về nhà)")) {
            Phat = 1000* Integer.parseInt(valueTH.getText());
        } else {
            Phat = 1000* Integer.parseInt(valueTH.getText());
        }
//        System.out.println(Phat);
            
        
//        ArrayList<DauSach> listPN = DauSachDAO.getInstance().selectByConditionSoPN(tenDS);
//        for (DauSach ds : listPN) {
//            ISBN = ds.getISBN();
//        }
//        SoLuong = Integer.parseInt(valueSPM.getText());
//        int Gia = 0;
//        ArrayList<Sach> listSach = SachDAO.getInstance().selectByConditionMaSach(ISBN,Integer.toString(NamXB));
//        for (Sach s : listSach) {
//            MaSach= s.getMaSach();
//        }
//
//                tableModel.setRowCount(0);
        tableModel = (DefaultTableModel) listTableAdd.getModel();
        tableModel.addRow(new Object[]{MaSach,tenDS, choiceVP,Long.toString(Phat)});
        defUI();
        this.listSach.remove(tenDS);



    }//GEN-LAST:event_addBtnActionPerformed

    private void upBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upBtnActionPerformed
        // TODO add your handling code here:

        if(upBtn.getText().equalsIgnoreCase("Sửa")) {
            if(listTableAdd.getSelectedRowCount() != 1) {
                JOptionPane.showMessageDialog(null, "Vui lòng chọn hàng muốn Sửa");
            } else {
                saveBtn.setVisible(true);
                upBtn.setText("Hủy");
                addBtn.setEnabled(false);
                delBTN.setEnabled(false);

                String chooseMaSach = tableModel.getValueAt(listTableAdd.getSelectedRow(), 0).toString();
                String chooseTenSach =tableModel.getValueAt(listTableAdd.getSelectedRow(), 1).toString();
                String chooseViPham = tableModel.getValueAt(listTableAdd.getSelectedRow(), 2).toString();
                 String choosePhat =tableModel.getValueAt(listTableAdd.getSelectedRow(), 3).toString();

                
                if(chooseViPham.equalsIgnoreCase("Trả tài liệu trễ hạn (tài liệu mượn về nhà)")){
                    txtTreHan.setVisible(true);
                    expectBtn.setVisible(true);
                    valueTH.setVisible(true);
                    plusBtn.setVisible(true);
                    valueTH.setText(Integer.toString(Integer.parseInt(choosePhat)/1000));
                } 
                

                if (chooseViPham.equalsIgnoreCase("Tài liệu mượn đọc tại chỗ nhưng hội viên cố tình đem về nhà")) {
                    txtTreHan.setVisible(true);
                    expectBtn.setVisible(true);
                    valueTH.setVisible(true);
                    plusBtn.setVisible(true);
                    valueTH.setText(Integer.toString(Integer.parseInt(choosePhat)/1000));
                } 
                
                listSach.removeAll();
                addListSach();

                //
                for (int i = 0; i < listSach.getItemCount(); i++) {
                    String item = listSach.getItem(i);
                    if(item.equalsIgnoreCase(chooseTenSach)){
                        listSach.select(i);
                    }
                }
                
                

                for (int i = 0; i < choiceListVP.getItemCount(); i++) {
                    String item = choiceListVP.getItem(i);
                    if(item.equalsIgnoreCase(chooseViPham)){
                        choiceListVP.select(i);
                    }
                }


             
                

            }
        }
        else {
            defUI();
            saveBtn.setVisible(false);
            upBtn.setText("Sửa");
            addBtn.setEnabled(true);
            delBTN.setEnabled(true);
            JOptionPane.showMessageDialog(null, "Hủy Sửa thành công");

        }
    }//GEN-LAST:event_upBtnActionPerformed

    private void delBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBTNActionPerformed
        // TODO add your handling code here:
        if(listTableAdd.getSelectedRowCount() != 1) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn hàng muốn Xóa");
        } else {
            int[] selectedRows = listTableAdd.getSelectedRows();
            if (selectedRows.length > 0) {
                for (int i = selectedRows.length - 1; i >= 0; i--) {
                    tableModel.removeRow(selectedRows[i]);
                }
            }
        }
        listSach.removeAll();
        addListSach();
    }//GEN-LAST:event_delBTNActionPerformed

    private void listSachItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_listSachItemStateChanged
        // TODO add your handling code here:
        tenDS = listSach.getItem(listSach.getSelectedIndex());
        
//        listNamXB.removeAll();
//        addListNamXB();
    }//GEN-LAST:event_listSachItemStateChanged

    private void choiceListVPItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_choiceListVPItemStateChanged
        // TODO add your handling code here:
        choiceVP = choiceListVP.getItem(choiceListVP.getSelectedIndex());
        
        if(choiceVP.equalsIgnoreCase("Trả tài liệu trễ hạn (tài liệu mượn về nhà)")) {
                   txtTreHan.setVisible(true);
                    expectBtn.setVisible(true);
                    valueTH.setVisible(true);
                    plusBtn.setVisible(true); 
        }
        
        if (choiceVP.equalsIgnoreCase("Tài liệu mượn đọc tại chỗ nhưng hội viên cố tình đem về nhà")) {
                    txtTreHan.setVisible(true);
                    expectBtn.setVisible(true);
                    valueTH.setVisible(true);
                    plusBtn.setVisible(true); 
        }
    }//GEN-LAST:event_choiceListVPItemStateChanged

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:

        ArrayList<CTPhieuTra> listPT = CTPhieuTraDAO.getInstance().selectMaSachNotInPT(choiceTenDG, tenDS,1);
        for (CTPhieuTra pt : listPT) {
            MaSach = pt.getMaSach();
        } 
        if (MaSach.equalsIgnoreCase("")) {
           ArrayList<CTPhieuTra> listPT1 = CTPhieuTraDAO.getInstance().selectMaSachNotInPT(choiceTenDG, tenDS,2);
        for (CTPhieuTra pt : listPT1) {
            MaSach = pt.getMaSach();
        }  
        }
        System.out.println(MaSach);
        
        tenDS = listSach.getItem(listSach.getSelectedIndex());
        
        choiceVP = choiceListVP.getItem(choiceListVP.getSelectedIndex());

        int Gia = 0;
        ArrayList<Sach> listSach = SachDAO.getInstance().selectByConditionGia(MaSach, "", 2);
        for (Sach sach : listSach) {
            Gia = sach.getGia();
        }
        System.out.println(Gia);
        
        if(choiceVP.equalsIgnoreCase("Không vi phạm")){
            Phat= 0;
        }else if (choiceVP.equalsIgnoreCase("Mất tài liệu")) {
            Phat = Gia*3;
        } else if (choiceVP.equalsIgnoreCase("Tài liệu bị xé hoặc rách 1/3 trở lên")) {
            Phat = Gia*2;
        } else if (choiceVP.equalsIgnoreCase("Tài liệu bị bẩn, nhàu nát (ghi chép, gạch xóa, tô đậm)")) {
            Phat = Gia;
        } else if (choiceVP.equalsIgnoreCase("Trả tài liệu trễ hạn (tài liệu mượn về nhà)")) {
            Phat = 1000* Integer.parseInt(valueTH.getText());
        } else {
            Phat = 1000* Integer.parseInt(valueTH.getText());
        }
        System.out.println(Phat);
        
        //        tableModel.setRowCount(0);
        tableModel = (DefaultTableModel) listTableAdd.getModel();
        tableModel.setValueAt(MaSach, listTableAdd.getSelectedRow(), 0);
        tableModel.setValueAt(tenDS, listTableAdd.getSelectedRow(), 1);
        tableModel.setValueAt(choiceVP, listTableAdd.getSelectedRow(), 2);
        tableModel.setValueAt(Phat, listTableAdd.getSelectedRow(), 3);

        defUI();
        this.listSach.remove(tenDS);

        upBtn.setText("Sửa");
        saveBtn.setVisible(false);
        addBtn.setEnabled(true);
        delBTN.setEnabled(true);
    }//GEN-LAST:event_saveBtnActionPerformed

    private void choiceListNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_choiceListNameItemStateChanged
        // TODO add your handling code here:
        choiceTenDG = choiceListName.getItem(choiceListName.getSelectedIndex());
        listSach.removeAll();
        addListSach();
        choiceListName.setEnabled(false);
    }//GEN-LAST:event_choiceListNameItemStateChanged

    private void expectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expectBtnActionPerformed
        // TODO add your handling code here:
        int expectValue = Integer.parseInt(valueTH.getText());
        expectValue -=1;
        valueTH.setText(Integer.toString(expectValue));
    }//GEN-LAST:event_expectBtnActionPerformed

    private void plusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusBtnActionPerformed
        // TODO add your handling code here:
        int plusValue = Integer.parseInt(valueTH.getText());
        plusValue +=1;
        valueTH.setText(Integer.toString(plusValue));
    }//GEN-LAST:event_plusBtnActionPerformed

    private void valueTHPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_valueTHPropertyChange
        // TODO add your handling code here:
        if (Integer.parseInt(valueTH.getText()) <= 0) {
            expectBtn.setEnabled(false);
        } else {
            expectBtn.setEnabled(true);
        }
        
//        if(Integer.parseInt(valueTH.getText()) >= 1) {
//            plusBtn.setEnabled(false);
//        }else {
//            plusBtn.setEnabled(true);
//        }
    }//GEN-LAST:event_valueTHPropertyChange

    private void mainPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainPTActionPerformed
        // TODO add your handling code here:
        QuanLyPhieuTra mainLyPhieuTra = new QuanLyPhieuTra();
        setVisible(false);
    }//GEN-LAST:event_mainPTActionPerformed

    private void mainBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainBtnActionPerformed
        // TODO add your handling code here:
         Main main = new Main();
        setVisible(false);
    }//GEN-LAST:event_mainBtnActionPerformed

    private void thoatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thoatBtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_thoatBtnActionPerformed

    private void menuMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMainActionPerformed
        // TODO add your handling code here:
        Main main = new Main();
        setVisible(false);
    }//GEN-LAST:event_menuMainActionPerformed

    private void menuDGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDGActionPerformed
        // TODO add your handling code here:
        QuanLyDG mainDG = new QuanLyDG();
        setVisible(false);
    }//GEN-LAST:event_menuDGActionPerformed

    private void menuTheDGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTheDGActionPerformed
        // TODO add your handling code here:
        QuanLyThe mainThe = new QuanLyThe();
        setVisible(false);
    }//GEN-LAST:event_menuTheDGActionPerformed

    private void menuQuanLyTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuQuanLyTTActionPerformed
        // TODO add your handling code here:
        QuanLyThuThu mainTT = new QuanLyThuThu();
        setVisible(false);
    }//GEN-LAST:event_menuQuanLyTTActionPerformed

    private void menuQuanLyDauSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuQuanLyDauSachActionPerformed
        // TODO add your handling code here:
        QuanLyDauSach mainQuanLyDauSach = new QuanLyDauSach();
        setVisible(false);
    }//GEN-LAST:event_menuQuanLyDauSachActionPerformed

    private void menuNhapSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNhapSachActionPerformed
        // TODO add your handling code here:
        QuanLyPhieuNhap mainLyPhieuNhap = new QuanLyPhieuNhap();
        setVisible(false);
    }//GEN-LAST:event_menuNhapSachActionPerformed

    private void menuThemPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuThemPNActionPerformed
        // TODO add your handling code here:
        QuanLyThemPN menQuanLyThemPN = new QuanLyThemPN();
        setVisible(false);
    }//GEN-LAST:event_menuThemPNActionPerformed

    private void menuNhaCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNhaCCActionPerformed
        // TODO add your handling code here:
        QuanLyNhaCungCap mainNCC = new QuanLyNhaCungCap();
        setVisible(false);
    }//GEN-LAST:event_menuNhaCCActionPerformed

    private void menuQuanLyMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuQuanLyMuonActionPerformed
        // TODO add your handling code here:
        QuanLyMuon mainMuon = new QuanLyMuon();
        setVisible(false);
    }//GEN-LAST:event_menuQuanLyMuonActionPerformed

    private void menuThemPhieuMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuThemPhieuMuonActionPerformed
        // TODO add your handling code here:
        QuanLyThemPM mainThemPM = new QuanLyThemPM();
        setVisible(false);
    }//GEN-LAST:event_menuThemPhieuMuonActionPerformed

    private void menuQuanLyPhieuTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuQuanLyPhieuTraActionPerformed
        // TODO add your handling code here:
        QuanLyPhieuTra mainQuanLyPhieuTra = new QuanLyPhieuTra();
        setVisible(false);
    }//GEN-LAST:event_menuQuanLyPhieuTraActionPerformed

    private void menuQuanLyThemPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuQuanLyThemPTActionPerformed
        // TODO add your handling code here:
        QuanLyThemPT mainThemPT = new QuanLyThemPT();
        setVisible(false);
    }//GEN-LAST:event_menuQuanLyThemPTActionPerformed

    private void menuThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuThongKeActionPerformed
        // TODO add your handling code here:
        ThongKe mainTk = new ThongKe();
        setVisible(false);
    }//GEN-LAST:event_menuThongKeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyThemPT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyThemPT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyThemPT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyThemPT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyThemPT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton addPMBTN;
    private java.awt.Choice choiceListName;
    private java.awt.Choice choiceListVP;
    private javax.swing.JButton delBTN;
    private javax.swing.JButton expectBtn;
    private com.toedter.calendar.JDateChooser inputNgayTra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private java.awt.Choice listSach;
    private javax.swing.JTable listTableAdd;
    private javax.swing.JButton mainBtn;
    private javax.swing.JButton mainPT;
    private javax.swing.JMenuItem menuDG;
    private javax.swing.JMenuItem menuMain;
    private javax.swing.JMenuItem menuNhaCC;
    private javax.swing.JMenuItem menuNhapSach;
    private javax.swing.JMenuItem menuQuanLyDauSach;
    private javax.swing.JMenuItem menuQuanLyMuon;
    private javax.swing.JMenuItem menuQuanLyPhieuTra;
    private javax.swing.JMenuItem menuQuanLyTT;
    private javax.swing.JMenuItem menuQuanLyThemPT;
    private javax.swing.JMenuItem menuTheDG;
    private javax.swing.JMenuItem menuThemPN;
    private javax.swing.JMenuItem menuThemPhieuMuon;
    private javax.swing.JMenuItem menuThongKe;
    private javax.swing.JButton plusBtn;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton thoatBtn;
    private javax.swing.JLabel txtTreHan;
    private javax.swing.JButton upBtn;
    private javax.swing.JLabel valueTH;
    // End of variables declaration//GEN-END:variables
}
