/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import DAO.PhieuNhapToHopDAO;
import DAO.TheThuVienDAO;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.PointerInfo;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.DocGia;
import model.PhieuNhapToHop;

/**
 *
 * @author minht
 */
public class QuanLyPhieuNhap extends javax.swing.JFrame {

    List<PhieuNhapToHop> listPN = new ArrayList<>();
    DefaultTableModel tableModel = null;
//    public static String selectedList;
    
    public static String chose;

    
      public void showData(){
         listPN = PhieuNhapToHopDAO.getInstance().selectPhieuNhapToHop();
         tableModel.setRowCount(0);
         listPN.forEach((pn) -> {
            tableModel.addRow(new Object[] {pn.getSoPN(), pn.getTenNCC(), pn.getNgayTao(),pn.getNgayNhap(),pn.getTongThanhTien()});
        });

    }
      

      
      
    

    public QuanLyPhieuNhap() {
        initComponents();
        choiceListFilter.addItem("Ngày tạo");
        choiceListFilter.addItem("Ngày nhập");
        
        setTitle("Quản lý phiếu nhập");
        setVisible(true);
        
        getContentPane().setBackground(new java.awt.Color(245,245,245));
        //set vị trí from ở trung tâm
        setLocationRelativeTo(null);
        
        tableModel = (DefaultTableModel) table.getModel();
        table.setDefaultEditor(Object.class, null);
        showData();
        inputAnotherChoose.setVisible(false);
        
        choiceListFilter.select(0);
        chose = choiceListFilter.getItem(0);
//        System.out.println(chose);
        
        
                inputAnotherChoose.addPropertyChangeListener(new PropertyChangeListener (){
            @Override
            public void propertyChange(PropertyChangeEvent evt){
                if(chose.equalsIgnoreCase("Ngày tạo")) {
                    if("date".equals(evt.getPropertyName())) {
                    Date selectedDate = (Date) evt.getNewValue();
                    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                    String newDate = dateFormat.format(selectedDate.getTime());
                    // Thực hiện xử lý sau khi người dùng thay đổi ngày
                    tableModel = (DefaultTableModel) table.getModel();
                     tableModel.setRowCount(0); 
                   
        
                    listPN = PhieuNhapToHopDAO.getInstance().selectByCondition(newDate,1);
                    tableModel.setRowCount(0);
                    listPN.forEach((pn) -> {
                      tableModel.addRow(new Object[] {pn.getSoPN(), pn.getTenNCC(), pn.getNgayTao(),pn.getNgayNhap(),pn.getTongThanhTien()});
                     });
                    
                    if (table.getRowCount() == 0) {
                        JOptionPane.showMessageDialog(null, "Không có dữ liệu"); 
                        showData();
                    }
                    }
                }
                else {
                   if("date".equals(evt.getPropertyName())) {
                    Date selectedDate = (Date) evt.getNewValue();
                    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                    String newDate = dateFormat.format(selectedDate.getTime());
                    // Thực hiện xử lý sau khi người dùng thay đổi ngày
                    tableModel = (DefaultTableModel) table.getModel();
                     tableModel.setRowCount(0); 
                   
        
                    listPN = PhieuNhapToHopDAO.getInstance().selectByCondition(newDate,3);
                    tableModel.setRowCount(0);
                    listPN.forEach((pn) -> {
                      tableModel.addRow(new Object[] {pn.getSoPN(), pn.getTenNCC(), pn.getNgayTao(),pn.getNgayNhap(),pn.getTongThanhTien()});
                     });
                    
                    if (table.getRowCount() == 0) {
                        JOptionPane.showMessageDialog(null, "Không có dữ liệu");  
                        showData();

                    }
                    
                    } 
                }
            }
        });
        

    }
    
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel6 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        inputSearchSoPN = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        searchBtn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        filterPanel = new javax.swing.JPanel();
        todayChooce = new javax.swing.JRadioButton();
        monthChoose = new javax.swing.JRadioButton();
        anotherChoose = new javax.swing.JRadioButton();
        inputAnotherChoose = new com.toedter.calendar.JDateChooser();
        choiceListFilter = new java.awt.Choice();
        yearChoice = new javax.swing.JRadioButton();
        lastyearChoice = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        thempnBTN = new javax.swing.JButton();
        btnMain = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuMain = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem8 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuDG = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        menuTheDG = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuQuanLyTT = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuQuanLyDauSach = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menuNhapSach = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        menuThemPN = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        menuNhaCC = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        menuQuanLyMuon = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        menuThemPhieuMuon = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuQuanLyPhieuTra = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        menuQuanLyThemPT = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        menuThongKe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel6.setBackground(new java.awt.Color(27, 70, 139));
        jPanel6.setPreferredSize(new java.awt.Dimension(0, 20));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel10.setBackground(new java.awt.Color(27, 70, 139));
        jPanel10.setPreferredSize(new java.awt.Dimension(0, 20));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(252, 252, 255));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(27, 70, 139));
        jLabel10.setText("TRƯỜNG ĐẠI HỌC TÀI CHÍNH MARKETING");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(27, 70, 139));
        jLabel11.setText("THƯ VIỆN");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(0, 652, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(70, 67));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thuvien/img/miniLogo.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(245, 245, 245));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel4.setText("Số phiếu nhập :");

        searchBtn.setText("Tìm kiếm");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(searchBtn)
                    .addComponent(inputSearchSoPN, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jLabel4)
                    .addContainerGap(210, Short.MAX_VALUE)))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(inputSearchSoPN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(searchBtn)
                .addGap(16, 16, 16))
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(19, 19, 19)
                    .addComponent(jLabel4)
                    .addContainerGap(55, Short.MAX_VALUE)))
        );

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(27, 70, 139));
        jLabel12.setText("Tìm kiếm");

        filterPanel.setBackground(new java.awt.Color(245, 245, 245));
        filterPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        filterPanel.setPreferredSize(new java.awt.Dimension(310, 200));

        buttonGroup1.add(todayChooce);
        todayChooce.setText("Hôm nay");
        todayChooce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todayChooceActionPerformed(evt);
            }
        });

        buttonGroup1.add(monthChoose);
        monthChoose.setText("Tháng hiện tại");
        monthChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthChooseActionPerformed(evt);
            }
        });

        buttonGroup1.add(anotherChoose);
        anotherChoose.setText("Lựa chọn khác");
        anotherChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anotherChooseActionPerformed(evt);
            }
        });

        inputAnotherChoose.setDateFormatString("dd-MM-yyyy");

        choiceListFilter.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                choiceListFilterItemStateChanged(evt);
            }
        });

        buttonGroup1.add(yearChoice);
        yearChoice.setText("Năm hiện tại");
        yearChoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearChoiceActionPerformed(evt);
            }
        });

        buttonGroup1.add(lastyearChoice);
        lastyearChoice.setText("Năm trước");
        lastyearChoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastyearChoiceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout filterPanelLayout = new javax.swing.GroupLayout(filterPanel);
        filterPanel.setLayout(filterPanelLayout);
        filterPanelLayout.setHorizontalGroup(
            filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(monthChoose)
                    .addComponent(choiceListFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(todayChooce)
                    .addComponent(yearChoice)
                    .addComponent(anotherChoose)
                    .addComponent(lastyearChoice)
                    .addComponent(inputAnotherChoose, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        filterPanelLayout.setVerticalGroup(
            filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filterPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(choiceListFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(todayChooce)
                .addGap(18, 18, 18)
                .addComponent(monthChoose)
                .addGap(18, 18, 18)
                .addComponent(yearChoice)
                .addGap(18, 18, 18)
                .addComponent(lastyearChoice)
                .addGap(18, 18, 18)
                .addComponent(anotherChoose)
                .addGap(18, 18, 18)
                .addComponent(inputAnotherChoose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jLabel13.setBackground(new java.awt.Color(27, 70, 139));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(27, 70, 139));
        jLabel13.setText("Lọc theo ngày");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(27, 70, 139));
        jLabel2.setText("THÔNG TIN NHẬP SÁCH");

        jPanel3.setBackground(new java.awt.Color(245, 245, 245));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "Danh sách phiếu nhập", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Số Phiếu Nhập", "Tên Nhà Cung Cấp", "Ngày Tạo ", "Ngày Nhập ", "Tổng Thành Tiền"
            }
        ));
        table.setRowHeight(30);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        thempnBTN.setText("Thêm Phiếu Nhập");
        thempnBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thempnBTNActionPerformed(evt);
            }
        });

        btnMain.setText("Trang Chủ");
        btnMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainActionPerformed(evt);
            }
        });

        jButton3.setText("Thoát");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jMenuBar1.setBackground(new java.awt.Color(204, 204, 204));
        jMenuBar1.setOpaque(true);

        jMenu1.setText("Tiện ích");
        jMenu1.setMargin(new java.awt.Insets(3, 12, 3, 12));

        menuMain.setText("Trang chủ");
        menuMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMainActionPerformed(evt);
            }
        });
        jMenu1.add(menuMain);
        jMenu1.add(jSeparator2);

        jMenuItem8.setText("Giới thiệu");
        jMenu1.add(jMenuItem8);
        jMenu1.add(jSeparator3);

        jMenuItem9.setText("Thông tin liên hệ");
        jMenu1.add(jMenuItem9);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Quản lý độc giả");
        jMenu2.setMargin(new java.awt.Insets(3, 12, 3, 12));

        menuDG.setText("Danh sách độc giả");
        menuDG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDGActionPerformed(evt);
            }
        });
        jMenu2.add(menuDG);
        jMenu2.add(jSeparator4);

        menuTheDG.setText("Danh sách thẻ độc giả");
        menuTheDG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTheDGActionPerformed(evt);
            }
        });
        jMenu2.add(menuTheDG);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Quản lý thu thư");
        jMenu3.setMargin(new java.awt.Insets(3, 12, 3, 12));

        menuQuanLyTT.setText("Danh mục thủ thư");
        menuQuanLyTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuQuanLyTTActionPerformed(evt);
            }
        });
        jMenu3.add(menuQuanLyTT);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Quản lý sách");
        jMenu4.setMargin(new java.awt.Insets(3, 12, 3, 12));

        menuQuanLyDauSach.setText("Danh mục đầu sách");
        menuQuanLyDauSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuQuanLyDauSachActionPerformed(evt);
            }
        });
        jMenu4.add(menuQuanLyDauSach);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Quản lý nhập sách");
        jMenu5.setMargin(new java.awt.Insets(3, 12, 3, 12));

        menuNhapSach.setText("Danh mục nhập sách");
        menuNhapSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNhapSachActionPerformed(evt);
            }
        });
        jMenu5.add(menuNhapSach);
        jMenu5.add(jSeparator6);

        menuThemPN.setText("Thêm Phiếu nhập");
        menuThemPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuThemPNActionPerformed(evt);
            }
        });
        jMenu5.add(menuThemPN);
        jMenu5.add(jSeparator5);

        menuNhaCC.setText("Danh mục nhà cung cấp");
        menuNhaCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNhaCCActionPerformed(evt);
            }
        });
        jMenu5.add(menuNhaCC);

        jMenuBar1.add(jMenu5);

        jMenu7.setText("Quản lý mượn - trả");
        jMenu7.setMargin(new java.awt.Insets(3, 12, 3, 12));

        menuQuanLyMuon.setText("Danh sách mượn");
        menuQuanLyMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuQuanLyMuonActionPerformed(evt);
            }
        });
        jMenu7.add(menuQuanLyMuon);
        jMenu7.add(jSeparator7);

        menuThemPhieuMuon.setText("Thêm phiếu mượn");
        menuThemPhieuMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuThemPhieuMuonActionPerformed(evt);
            }
        });
        jMenu7.add(menuThemPhieuMuon);
        jMenu7.add(jSeparator1);

        menuQuanLyPhieuTra.setText("Danh sách trả");
        menuQuanLyPhieuTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuQuanLyPhieuTraActionPerformed(evt);
            }
        });
        jMenu7.add(menuQuanLyPhieuTra);
        jMenu7.add(jSeparator8);

        menuQuanLyThemPT.setText("Thêm phiếu trả");
        menuQuanLyThemPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuQuanLyThemPTActionPerformed(evt);
            }
        });
        jMenu7.add(menuQuanLyThemPT);

        jMenuBar1.add(jMenu7);

        jMenu8.setText("Tổng thống kê");
        jMenu8.setMargin(new java.awt.Insets(3, 12, 3, 12));

        menuThongKe.setText("Thống kê");
        menuThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuThongKeActionPerformed(evt);
            }
        });
        jMenu8.add(menuThongKe);

        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 1043, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 1043, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel12))
                    .addComponent(filterPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(thempnBTN)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnMain)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(16, 16, 16))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(thempnBTN))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMain)
                    .addComponent(jButton3))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainActionPerformed
        // TODO add your handling code here:
        Main main = new Main();
        setVisible(false);
    }//GEN-LAST:event_btnMainActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void anotherChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anotherChooseActionPerformed
        // TODO add your handling code here:
        if(anotherChoose.isSelected()){
          inputAnotherChoose.setVisible(true);
        }
    }//GEN-LAST:event_anotherChooseActionPerformed

    private void choiceListFilterItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_choiceListFilterItemStateChanged
        // TODO add your handling code here:
        chose = choiceListFilter.getItem(choiceListFilter.getSelectedIndex());
    }//GEN-LAST:event_choiceListFilterItemStateChanged

    private void todayChooceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todayChooceActionPerformed
        // TODO add your handling code here:
        inputAnotherChoose.setVisible(false);
        
        if(todayChooce.isSelected() && chose.equalsIgnoreCase("Ngày tạo")) {
            
        tableModel = (DefaultTableModel) table.getModel();
        tableModel.setRowCount(0);
        Calendar cal = Calendar.getInstance();
        SimpleDateFormat dateOnly = new SimpleDateFormat("yyyy/MM/dd");
        String date = dateOnly.format(cal.getTime());
        
         listPN = PhieuNhapToHopDAO.getInstance().selectByCondition(date,1);
         tableModel.setRowCount(0);
         listPN.forEach((pn) -> {
            tableModel.addRow(new Object[] {pn.getSoPN(), pn.getTenNCC(), pn.getNgayTao(),pn.getNgayNhap(),pn.getTongThanhTien()});
        });
         
         if (table.getRowCount() == 0) {
           JOptionPane.showMessageDialog(null, "Không có dữ liệu"); 
           showData();

        }
         
         
        } 
        else {
           tableModel = (DefaultTableModel) table.getModel();
            tableModel.setRowCount(0);
            Calendar cal = Calendar.getInstance();
            SimpleDateFormat dateOnly = new SimpleDateFormat("yyyy/MM/dd");
            String date = dateOnly.format(cal.getTime());
        
         listPN = PhieuNhapToHopDAO.getInstance().selectByCondition(date,3);
         tableModel.setRowCount(0);
         listPN.forEach((pn) -> {
            tableModel.addRow(new Object[] {pn.getSoPN(), pn.getTenNCC(), pn.getNgayTao(),pn.getNgayNhap(),pn.getTongThanhTien()});
        }); 
         
         if (table.getRowCount() == 0) {
          JOptionPane.showMessageDialog(null, "Không có dữ liệu");  
          showData();

          }
        }

    }//GEN-LAST:event_todayChooceActionPerformed

    private void monthChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthChooseActionPerformed
        // TODO add your handling code here:
        inputAnotherChoose.setVisible(false);
        
        if(monthChoose.isSelected() && chose.equalsIgnoreCase("Ngày tạo")){
           tableModel = (DefaultTableModel) table.getModel();
           tableModel.setRowCount(0); 
           LocalDate today = LocalDate.now();
           String month = Integer.toString(today.getMonthValue());
         listPN = PhieuNhapToHopDAO.getInstance().selectByCondition(month,2);
         tableModel.setRowCount(0);
         listPN.forEach((pn) -> {
            tableModel.addRow(new Object[] {pn.getSoPN(), pn.getTenNCC(), pn.getNgayTao(),pn.getNgayNhap(),pn.getTongThanhTien()});
        }); 
         
         if (table.getRowCount() == 0) {
          JOptionPane.showMessageDialog(null, "Không có dữ liệu"); 
          showData();
          }
        } 
        else {
          tableModel = (DefaultTableModel) table.getModel();
           tableModel.setRowCount(0); 
           LocalDate today = LocalDate.now();
           String month = Integer.toString(today.getMonthValue());
            listPN = PhieuNhapToHopDAO.getInstance().selectByCondition(month,4);
            tableModel.setRowCount(0);
            listPN.forEach((pn) -> {
            tableModel.addRow(new Object[] {pn.getSoPN(), pn.getTenNCC(), pn.getNgayTao(),pn.getNgayNhap(),pn.getTongThanhTien()});
        }); 
            
            if (table.getRowCount() == 0) {
             JOptionPane.showMessageDialog(null, "Không có dữ liệu");
             showData();
  
          }
        }
    }//GEN-LAST:event_monthChooseActionPerformed

    private void yearChoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearChoiceActionPerformed
        // TODO add your handling code here:
        inputAnotherChoose.setVisible(false);

        
        if(yearChoice.isSelected() && chose.equalsIgnoreCase("Ngày tạo")){
           tableModel = (DefaultTableModel) table.getModel();
           tableModel.setRowCount(0); 
         listPN = PhieuNhapToHopDAO.getInstance().selectByCondition("",5);
         tableModel.setRowCount(0);
         listPN.forEach((pn) -> {
            tableModel.addRow(new Object[] {pn.getSoPN(), pn.getTenNCC(), pn.getNgayTao(),pn.getNgayNhap(),pn.getTongThanhTien()});
        }); 
         
         if (table.getRowCount() == 0) {
          JOptionPane.showMessageDialog(null, "Không có dữ liệu"); 
          showData();
          }
        } 
        else {
          tableModel = (DefaultTableModel) table.getModel();
           tableModel.setRowCount(0); 
            listPN = PhieuNhapToHopDAO.getInstance().selectByCondition("",6);
            tableModel.setRowCount(0);
            listPN.forEach((pn) -> {
            tableModel.addRow(new Object[] {pn.getSoPN(), pn.getTenNCC(), pn.getNgayTao(),pn.getNgayNhap(),pn.getTongThanhTien()});
        }); 
            
            if (table.getRowCount() == 0) {
             JOptionPane.showMessageDialog(null, "Không có dữ liệu");
             showData();
  
          }
        }
    }//GEN-LAST:event_yearChoiceActionPerformed

    private void lastyearChoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastyearChoiceActionPerformed
        // TODO add your handling code here:
        inputAnotherChoose.setVisible(false);

        
        if(lastyearChoice.isSelected() && chose.equalsIgnoreCase("Ngày tạo")){
           tableModel = (DefaultTableModel) table.getModel();
           tableModel.setRowCount(0); 
         listPN = PhieuNhapToHopDAO.getInstance().selectByCondition("",7);
         tableModel.setRowCount(0);
         listPN.forEach((pn) -> {
            tableModel.addRow(new Object[] {pn.getSoPN(), pn.getTenNCC(), pn.getNgayTao(),pn.getNgayNhap(),pn.getTongThanhTien()});
        }); 
         
         if (table.getRowCount() == 0) {
          JOptionPane.showMessageDialog(null, "Không có dữ liệu"); 
          showData();
          }
        } 
        else {
          tableModel = (DefaultTableModel) table.getModel();
           tableModel.setRowCount(0); 
            listPN = PhieuNhapToHopDAO.getInstance().selectByCondition("",8);
            tableModel.setRowCount(0);
            listPN.forEach((pn) -> {
            tableModel.addRow(new Object[] {pn.getSoPN(), pn.getTenNCC(), pn.getNgayTao(),pn.getNgayNhap(),pn.getTongThanhTien()});
        }); 
            
            if (table.getRowCount() == 0) {
             JOptionPane.showMessageDialog(null, "Không có dữ liệu");
             showData();
  
          }
        }
    }//GEN-LAST:event_lastyearChoiceActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        String inputSoPn = inputSearchSoPN.getText();
        if (inputSoPn.equalsIgnoreCase("")){
           JOptionPane.showMessageDialog(null, "Vui lòng Nhập Số Phiếu Nhập cần tìm");
           showData(); 
        }else {
         tableModel = (DefaultTableModel) table.getModel();
         tableModel.setRowCount(0); 
         listPN = PhieuNhapToHopDAO.getInstance().selectByCondition(inputSoPn,9);
         tableModel.setRowCount(0);
         listPN.forEach((pn) -> {
            tableModel.addRow(new Object[] {pn.getSoPN(), pn.getTenNCC(), pn.getNgayTao(),pn.getNgayNhap(),pn.getTongThanhTien()});
        }); 
        
         
         if (table.getRowCount() == 0) {
          JOptionPane.showMessageDialog(null, "Không có dữ liệu"); 
          showData();
          inputSearchSoPN.setText("");
          }
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        String SoPN = tableModel.getValueAt(table.getSelectedRow(), 0).toString();
        System.out.println(SoPN);
//        chitietpnDialog ctpn = new chitietpnDialog(this, false, SoPN);
        chitietpnDialog ct = new chitietpnDialog(this, false, SoPN);
        
    }//GEN-LAST:event_tableMouseClicked

    private void thempnBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thempnBTNActionPerformed
        // TODO add your handling code here:
        QuanLyThemPN themPN = new QuanLyThemPN();
        setVisible(false);
    }//GEN-LAST:event_thempnBTNActionPerformed

    private void menuMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMainActionPerformed
        // TODO add your handling code here:
        Main main = new Main();
        setVisible(false);
    }//GEN-LAST:event_menuMainActionPerformed

    private void menuDGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDGActionPerformed
        // TODO add your handling code here:
        QuanLyDG mainDG = new QuanLyDG();
        setVisible(false);
    }//GEN-LAST:event_menuDGActionPerformed

    private void menuTheDGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTheDGActionPerformed
        // TODO add your handling code here:
        QuanLyThe mainThe = new QuanLyThe();
        setVisible(false);
    }//GEN-LAST:event_menuTheDGActionPerformed

    private void menuQuanLyTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuQuanLyTTActionPerformed
        // TODO add your handling code here:
        QuanLyThuThu mainTT = new QuanLyThuThu();
        setVisible(false);
    }//GEN-LAST:event_menuQuanLyTTActionPerformed

    private void menuQuanLyDauSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuQuanLyDauSachActionPerformed
        // TODO add your handling code here:
        QuanLyDauSach mainQuanLyDauSach = new QuanLyDauSach();
        setVisible(false);
    }//GEN-LAST:event_menuQuanLyDauSachActionPerformed

    private void menuNhapSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNhapSachActionPerformed
        // TODO add your handling code here:
        QuanLyPhieuNhap mainLyPhieuNhap = new QuanLyPhieuNhap();
        setVisible(false);
    }//GEN-LAST:event_menuNhapSachActionPerformed

    private void menuThemPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuThemPNActionPerformed
        // TODO add your handling code here:
        QuanLyThemPN menQuanLyThemPN = new QuanLyThemPN();
        setVisible(false);
    }//GEN-LAST:event_menuThemPNActionPerformed

    private void menuNhaCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNhaCCActionPerformed
        // TODO add your handling code here:
        QuanLyNhaCungCap mainNCC = new QuanLyNhaCungCap();
        setVisible(false);
    }//GEN-LAST:event_menuNhaCCActionPerformed

    private void menuQuanLyMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuQuanLyMuonActionPerformed
        // TODO add your handling code here:
        QuanLyMuon mainMuon = new QuanLyMuon();
        setVisible(false);
    }//GEN-LAST:event_menuQuanLyMuonActionPerformed

    private void menuThemPhieuMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuThemPhieuMuonActionPerformed
        // TODO add your handling code here:
        QuanLyThemPM mainThemPM = new QuanLyThemPM();
        setVisible(false);
    }//GEN-LAST:event_menuThemPhieuMuonActionPerformed

    private void menuQuanLyPhieuTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuQuanLyPhieuTraActionPerformed
        // TODO add your handling code here:
        QuanLyPhieuTra mainQuanLyPhieuTra = new QuanLyPhieuTra();
        setVisible(false);
    }//GEN-LAST:event_menuQuanLyPhieuTraActionPerformed

    private void menuQuanLyThemPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuQuanLyThemPTActionPerformed
        // TODO add your handling code here:
        QuanLyThemPT mainThemPT = new QuanLyThemPT();
        setVisible(false);
    }//GEN-LAST:event_menuQuanLyThemPTActionPerformed

    private void menuThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuThongKeActionPerformed
        // TODO add your handling code here:
        ThongKe mainTk = new ThongKe();
        setVisible(false);
    }//GEN-LAST:event_menuThongKeActionPerformed
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhieuNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhieuNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhieuNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhieuNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyPhieuNhap().setVisible(true);
            }
        });
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton anotherChoose;
    private javax.swing.JButton btnMain;
    private javax.swing.ButtonGroup buttonGroup1;
    private java.awt.Choice choiceListFilter;
    private javax.swing.JPanel filterPanel;
    private com.toedter.calendar.JDateChooser inputAnotherChoose;
    private javax.swing.JTextField inputSearchSoPN;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JRadioButton lastyearChoice;
    private javax.swing.JMenuItem menuDG;
    private javax.swing.JMenuItem menuMain;
    private javax.swing.JMenuItem menuNhaCC;
    private javax.swing.JMenuItem menuNhapSach;
    private javax.swing.JMenuItem menuQuanLyDauSach;
    private javax.swing.JMenuItem menuQuanLyMuon;
    private javax.swing.JMenuItem menuQuanLyPhieuTra;
    private javax.swing.JMenuItem menuQuanLyTT;
    private javax.swing.JMenuItem menuQuanLyThemPT;
    private javax.swing.JMenuItem menuTheDG;
    private javax.swing.JMenuItem menuThemPN;
    private javax.swing.JMenuItem menuThemPhieuMuon;
    private javax.swing.JMenuItem menuThongKe;
    private javax.swing.JRadioButton monthChoose;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTable table;
    private javax.swing.JButton thempnBTN;
    private javax.swing.JRadioButton todayChooce;
    private javax.swing.JRadioButton yearChoice;
    // End of variables declaration//GEN-END:variables
}
