/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import DAO.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javafx.scene.paint.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.*;

/**
 *
 * @author minht
 */
public class QuanLyThe extends javax.swing.JFrame {
    List<TheThuVien> listTTV = new ArrayList<>();
    List<DocGia> listNewDG = new ArrayList<>();
    DefaultTableModel tableModelTTV = null;
    DefaultTableModel tableModelDG = null;


    boolean check = false;
    
    public void cleanUI(){
        inputMaThe.setText("");
        inputMaDG.setText("");
        inputNgayTao.setCalendar(null);
        inputHanThe.setCalendar(null);
        inputMaThe.setEnabled(false);
        inputMaDG.setEnabled(false);
        inputNgayTao.setEnabled(false);
        inputHanThe.setEnabled(false);
        btnSave.setVisible(false);
        btnUp.setEnabled(true);
        btnDel.setEnabled(true);
        txtMaDG1.setText("");
        txtHoTen.setText("" );
        txtNgaySinh.setText("" );
        txtGioiTinh.setText("" );
        txtDienThoai.setText("");
        txtDiaChi.setText("");
        txtDoiTuong.setText("");   
    }
    
        public void defUI(){
        inputMaThe.setText("");
        inputMaDG.setText("");
        inputHanThe.setCalendar(null);
        inputMaThe.setEnabled(true);
        inputMaDG.setEnabled(true);
        inputNgayTao.setEnabled(true);
        inputHanThe.setEnabled(true);
    }
    
   public void showData(){
         listTTV = TheThuVienDAO.getInstance().selectAll();
         tableModelTTV.setRowCount(0);
         listTTV.forEach((ttv) -> {
            tableModelTTV.addRow(new Object[] {ttv.getMaThe(), ttv.getMaDG(), ttv.getNgayTao(),ttv.getHanThe()});
        });

    }
      
    public void showDataNew(){
        listNewDG = DocGiaDAO.getInstance().selectNewDG();
         tableModelDG.setRowCount(0);
         listNewDG.forEach((DG) -> {
            tableModelDG.addRow(new Object[] {DG.getMaDG(), DG.getHoTenDG(), DG.getNgaySinhDG(),DG.getGioiTinhDG(),DG.getDienThoaiDG(),DG.getDiaChiDG(),DG.getDoiTuong()});
        });   
    }
    

      
    
    
    /**
     * Creates new form QuanLyThe
     */
    public QuanLyThe() {
        initComponents();
        setTitle("Quản lý thẻ thư viện");
        setVisible(true);
        getContentPane().setBackground(new java.awt.Color(245,245,245));
        //set vị trí from ở trung tâm
        setLocationRelativeTo(null);
        
        
        tableModelTTV = (DefaultTableModel) tableTTV.getModel();
        tableTTV.setDefaultEditor(Object.class, null);
        showData();
        
        tableModelDG = (DefaultTableModel) tableDG.getModel();
        tableDG.setDefaultEditor(Object.class, null);
        showDataNew();
        cleanUI();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtMaThe = new javax.swing.JLabel();
        txtMaDG = new javax.swing.JLabel();
        txtHanThe = new javax.swing.JLabel();
        inputMaThe = new javax.swing.JTextField();
        inputMaDG = new javax.swing.JTextField();
        inputHanThe = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        inputNgayTao = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtMaDG1 = new java.awt.Label();
        txtNgaySinh = new java.awt.Label();
        txtHoTen = new java.awt.Label();
        txtGioiTinh = new java.awt.Label();
        txtDienThoai = new java.awt.Label();
        txtDiaChi = new java.awt.Label();
        txtDoiTuong = new java.awt.Label();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTTV = new javax.swing.JTable();
        btnUp = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableDG = new javax.swing.JTable();
        btnTaoThe = new javax.swing.JButton();
        mainBTN = new javax.swing.JButton();
        closeBTN = new javax.swing.JButton();
        dgBTN = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuMain = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem8 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuDG = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        menuTheDG = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuQuanLyTT = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuQuanLyDauSach = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menuNhapSach = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        menuThemPN = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        menuNhaCC = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        menuQuanLyMuon = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        menuThemPhieuMuon = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuQuanLyPhieuTra = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        menuQuanLyThemPT = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        menuThongKe = new javax.swing.JMenuItem();

        jPanel9.setBackground(new java.awt.Color(27, 70, 139));
        jPanel9.setPreferredSize(new java.awt.Dimension(0, 20));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(245, 245, 245));
        setPreferredSize(new java.awt.Dimension(1030, 876));

        jPanel6.setBackground(new java.awt.Color(27, 70, 139));
        jPanel6.setPreferredSize(new java.awt.Dimension(0, 20));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1027, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel10.setBackground(new java.awt.Color(27, 70, 139));
        jPanel10.setPreferredSize(new java.awt.Dimension(0, 20));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1027, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(27, 70, 139));
        jLabel2.setText("QUẢN LÝ THẺ THƯ VIỆN");

        jPanel2.setBackground(new java.awt.Color(245, 245, 245));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "Thông tin chi tiết", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        txtMaThe.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtMaThe.setText("Mã Thẻ :");

        txtMaDG.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtMaDG.setText("Mã Độc Giả :");

        txtHanThe.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtHanThe.setText("Hạn thẻ :");

        inputHanThe.setDateFormatString("dd-MM-yyyy");

        jLabel13.setText("Ngày Tạo");

        inputNgayTao.setDateFormatString("dd-MM-yyyy");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(txtMaThe)
                        .addGap(18, 18, 18)
                        .addComponent(inputMaThe, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtMaDG)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel13)
                                .addComponent(txtHanThe)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(inputMaDG, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                            .addComponent(inputHanThe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inputNgayTao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaThe)
                    .addComponent(inputMaThe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaDG)
                    .addComponent(inputMaDG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(inputNgayTao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtHanThe, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(inputHanThe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        jPanel3.setBackground(new java.awt.Color(245, 245, 245));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "Thông tin hội viên tương ứng", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel3.setText("Mã Độc Giả :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel4.setText("Họ Tên        :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel5.setText("Ngày Sinh    :");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel6.setText("Giới Tính      :");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel8.setText("Điện Thoại :");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel9.setText("Đối Tượng :");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel12.setText("Địa Chỉ      :");

        txtMaDG1.setName(""); // NOI18N
        txtMaDG1.setText("1");

        txtNgaySinh.setText("1");

        txtHoTen.setName(""); // NOI18N
        txtHoTen.setText("1");

        txtGioiTinh.setText("1");

        txtDienThoai.setText("label1");

        txtDiaChi.setText("label1");

        txtDoiTuong.setText("label1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtHoTen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtMaDG1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel8))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtDoiTuong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(33, 33, 33))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addComponent(jLabel3))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(txtMaDG1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txtGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(88, 88, 88))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(txtDoiTuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jPanel4.setBackground(new java.awt.Color(245, 245, 245));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "Danh sách thẻ", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        tableTTV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Thẻ", "Mã Độc Giả", "Ngày Tạo", "Hạn Thẻ"
            }
        ));
        tableTTV.setRowHeight(30);
        tableTTV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableTTVMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableTTV);

        btnUp.setText("Sửa");
        btnUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpActionPerformed(evt);
            }
        });

        btnSave.setText("Lưu");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDel.setText("Xóa");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUp, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDel)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSave)
                    .addComponent(btnDel))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(70, 67));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thuvien/img/miniLogo.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        jPanel7.setBackground(new java.awt.Color(252, 252, 255));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(27, 70, 139));
        jLabel10.setText("TRƯỜNG ĐẠI HỌC TÀI CHÍNH MARKETING");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(27, 70, 139));
        jLabel11.setText("THƯ VIỆN");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(0, 636, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(245, 245, 245));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "Danh sách độc giả chưa tạo thẻ", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        tableDG.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Độc Giả", "Họ Tên", "Ngày Sinh", "Giới Tính", "Điện Thoại", "Địa chỉ", "Đối tượng"
            }
        ));
        tableDG.setRowHeight(30);
        jScrollPane2.setViewportView(tableDG);

        btnTaoThe.setText("Tạo thẻ");
        btnTaoThe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoTheActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnTaoThe, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTaoThe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        mainBTN.setText("Trang chủ");
        mainBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainBTNActionPerformed(evt);
            }
        });

        closeBTN.setText("Thoát");
        closeBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBTNActionPerformed(evt);
            }
        });

        dgBTN.setText("Quản lý độc giả");
        dgBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dgBTNActionPerformed(evt);
            }
        });

        jMenuBar1.setBackground(new java.awt.Color(204, 204, 204));
        jMenuBar1.setOpaque(true);

        jMenu1.setText("Tiện ích");
        jMenu1.setMargin(new java.awt.Insets(3, 12, 3, 12));

        menuMain.setText("Trang chủ");
        menuMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMainActionPerformed(evt);
            }
        });
        jMenu1.add(menuMain);
        jMenu1.add(jSeparator2);

        jMenuItem8.setText("Giới thiệu");
        jMenu1.add(jMenuItem8);
        jMenu1.add(jSeparator3);

        jMenuItem9.setText("Thông tin liên hệ");
        jMenu1.add(jMenuItem9);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Quản lý độc giả");
        jMenu2.setMargin(new java.awt.Insets(3, 12, 3, 12));

        menuDG.setText("Danh sách độc giả");
        menuDG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDGActionPerformed(evt);
            }
        });
        jMenu2.add(menuDG);
        jMenu2.add(jSeparator4);

        menuTheDG.setText("Danh sách thẻ độc giả");
        menuTheDG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTheDGActionPerformed(evt);
            }
        });
        jMenu2.add(menuTheDG);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Quản lý thu thư");
        jMenu3.setMargin(new java.awt.Insets(3, 12, 3, 12));

        menuQuanLyTT.setText("Danh mục thủ thư");
        menuQuanLyTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuQuanLyTTActionPerformed(evt);
            }
        });
        jMenu3.add(menuQuanLyTT);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Quản lý sách");
        jMenu4.setMargin(new java.awt.Insets(3, 12, 3, 12));

        menuQuanLyDauSach.setText("Danh mục đầu sách");
        menuQuanLyDauSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuQuanLyDauSachActionPerformed(evt);
            }
        });
        jMenu4.add(menuQuanLyDauSach);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Quản lý nhập sách");
        jMenu5.setMargin(new java.awt.Insets(3, 12, 3, 12));

        menuNhapSach.setText("Danh mục nhập sách");
        menuNhapSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNhapSachActionPerformed(evt);
            }
        });
        jMenu5.add(menuNhapSach);
        jMenu5.add(jSeparator6);

        menuThemPN.setText("Thêm Phiếu nhập");
        menuThemPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuThemPNActionPerformed(evt);
            }
        });
        jMenu5.add(menuThemPN);
        jMenu5.add(jSeparator5);

        menuNhaCC.setText("Danh mục nhà cung cấp");
        menuNhaCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNhaCCActionPerformed(evt);
            }
        });
        jMenu5.add(menuNhaCC);

        jMenuBar1.add(jMenu5);

        jMenu7.setText("Quản lý mượn - trả");
        jMenu7.setMargin(new java.awt.Insets(3, 12, 3, 12));

        menuQuanLyMuon.setText("Danh sách mượn");
        menuQuanLyMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuQuanLyMuonActionPerformed(evt);
            }
        });
        jMenu7.add(menuQuanLyMuon);
        jMenu7.add(jSeparator7);

        menuThemPhieuMuon.setText("Thêm phiếu mượn");
        menuThemPhieuMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuThemPhieuMuonActionPerformed(evt);
            }
        });
        jMenu7.add(menuThemPhieuMuon);
        jMenu7.add(jSeparator1);

        menuQuanLyPhieuTra.setText("Danh sách trả");
        menuQuanLyPhieuTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuQuanLyPhieuTraActionPerformed(evt);
            }
        });
        jMenu7.add(menuQuanLyPhieuTra);
        jMenu7.add(jSeparator8);

        menuQuanLyThemPT.setText("Thêm phiếu trả");
        menuQuanLyThemPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuQuanLyThemPTActionPerformed(evt);
            }
        });
        jMenu7.add(menuQuanLyThemPT);

        jMenuBar1.add(jMenu7);

        jMenu8.setText("Tổng thống kê");
        jMenu8.setMargin(new java.awt.Insets(3, 12, 3, 12));

        menuThongKe.setText("Thống kê");
        menuThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuThongKeActionPerformed(evt);
            }
        });
        jMenu8.add(menuThongKe);

        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(16, 16, 16))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1027, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 1027, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mainBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(dgBTN)
                .addGap(16, 16, 16)
                .addComponent(closeBTN)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 247, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(closeBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dgBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBTNActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeBTNActionPerformed

    private void mainBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainBTNActionPerformed
        // TODO add your handling code here:
        Main main = new Main();
        setVisible(false);
    }//GEN-LAST:event_mainBTNActionPerformed

    private void dgBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dgBTNActionPerformed
        // TODO add your handling code here:
        QuanLyDG mainDG = new QuanLyDG();
        setVisible(false);

    }//GEN-LAST:event_dgBTNActionPerformed

    private void tableTTVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableTTVMouseClicked
        // TODO add your handling code here:
        String chooseMaThe = tableModelTTV.getValueAt(tableTTV.getSelectedRow(), 0).toString();    
        String chooseMaDG = tableModelTTV.getValueAt(tableTTV.getSelectedRow(), 1).toString();
        String chooseNgayTao = tableModelTTV.getValueAt(tableTTV.getSelectedRow(), 2).toString();
        String chooseHanThe = tableModelTTV.getValueAt(tableTTV.getSelectedRow(), 3).toString();

        inputMaThe.setText(chooseMaThe);
        inputMaDG.setText(chooseMaDG);
        try {
           Date d = new SimpleDateFormat("yyyy-MM-dd").parse(chooseHanThe); 
           inputHanThe.setDate(d);
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        try {
            Date d = new SimpleDateFormat("yyyy-MM-dd").parse(chooseNgayTao); 
           inputNgayTao.setDate(d);
        } catch (Exception e) {
        }
        
        ArrayList<DocGia> listDG = DocGiaDAO.getInstance().selectedById(chooseMaDG);
        for (DocGia docGia : listDG) {
            txtMaDG1.setText(docGia.getMaDG());
            txtHoTen.setText(docGia.getHoTenDG());
            txtNgaySinh.setText(docGia.getNgaySinhDG());
            txtGioiTinh.setText(docGia.getGioiTinhDG());
            txtDienThoai.setText(docGia.getDienThoaiDG());
            txtDiaChi.setText(docGia.getDiaChiDG());
            txtDoiTuong.setText(docGia.getDoiTuong());                                                                          
        }
    }//GEN-LAST:event_tableTTVMouseClicked

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
       String maMaThe = inputMaThe.getText();
       String maMaDG = inputMaDG.getText();
       Date dateNT = inputNgayTao.getDate();
       String NgayTao = DateFormat.getDateInstance().format(dateNT);
       Date date = inputHanThe.getDate();
       String HanThe = DateFormat.getDateInstance().format(date);
       TheThuVien ttv1 = new TheThuVien(maMaThe,maMaDG,NgayTao,HanThe);
       try {
        TheThuVienDAO.getInstance().update(ttv1);
        JOptionPane.showMessageDialog(null, "Sửa Thẻ Thư Viện thành công");  
        showData();
        btnUp.setText("Sửa");     
        cleanUI();   
        } catch (Exception ex) {
         ex.printStackTrace();
        }
          
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnTaoTheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoTheActionPerformed
        // TODO add your handling code here:
        if(tableDG.getSelectedRowCount() != 1) {
          JOptionPane.showMessageDialog(null, "Vui lòng chọn hàng muốn Tạo"); 
        } else {
            String maThe = "";
            String splitMaThe = "";
            int newMaTheInt;
            String newMaTheString = "";
            ArrayList<TheThuVien> listNewMaTTV = TheThuVienDAO.getInstance().selectNewMaTT();
            for (TheThuVien theThuVien : listNewMaTTV) {
                maThe = theThuVien.getMaThe();
            }
            //Tách mã thẻ
            splitMaThe = maThe.substring(3);
            //Tạo mã thẻ mới
            newMaTheInt = Integer.valueOf(splitMaThe) + 1;
            //gộp mã thẻ lại
            newMaTheString = "TTV" + Integer.toString(newMaTheInt);
            
            
            String chooseMaDGNew = tableModelDG.getValueAt(tableDG.getSelectedRow(), 0).toString();
            
            DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
            Date date = new Date();
            String NgayTao = dateFormat.format(date);
            
//            DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
            String newYear = Integer.toString(Calendar.getInstance().get(Calendar.YEAR) + 4);
            LocalDate myDate = LocalDate.parse(newYear + "-12-30");
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
            String HanThe = myDate.format(formatter);
            
            TheThuVien ttv = new TheThuVien(newMaTheString, chooseMaDGNew, NgayTao,HanThe);
            try {
                TheThuVienDAO.getInstance().insert(ttv);
                JOptionPane.showMessageDialog(null, "Thêm Thẻ Thư Viên thành công");
                showData();
                showDataNew();
                cleanUI();
            } catch (Exception e) {
                e.printStackTrace();
            }
            
            
            
            
            

        }
    }//GEN-LAST:event_btnTaoTheActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        // TODO add your handling code here:
          if(tableTTV.getSelectedRowCount() != 1) {
          JOptionPane.showMessageDialog(null, "Vui lòng chọn hàng muốn Xóa"); 
        }
        else {
            int result = JOptionPane.showConfirmDialog(null, "Khi xóa thẻ thư viện trên sẽ xóa cả thông tin độc giả tương ứng \n Bạn có chắc chắn muốn xóa ?", "Xác nhận xóa", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            //Thao tác thêm khi chọn Yes/No
            if (result == JOptionPane.YES_OPTION){ //chọn yes
               String maThe = inputMaThe.getText();
               String maDG = inputMaDG.getText();
               
                Calendar dateNT = inputNgayTao.getCalendar();
                dateNT.set(Calendar.HOUR, 0);
                dateNT.set(Calendar.MINUTE, 0);
                dateNT.set(Calendar.MILLISECOND, 0);
                dateNT.set(Calendar.SECOND, 0);
                SimpleDateFormat dateFormatNT = new SimpleDateFormat("yyyy-MM-dd");
                String NgayTao = dateFormatNT.format(dateNT.getTime());
                
               
                Calendar date = inputHanThe.getCalendar();
                SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                String hanThe = dateFormat.format(date.getTime());          
                TheThuVien ttv = new TheThuVien(maThe, maDG,NgayTao, hanThe);
                
                 ArrayList<DocGia> listDG = DocGiaDAO.getInstance().selectAll();
                for (DocGia docGia : listDG) {
                if(maDG.equalsIgnoreCase(docGia.getMaDG())) {
                String HoTen = txtHoTen.getText();
                String NgaySinh = txtNgaySinh.getText();
                String GioiTinh = txtGioiTinh.getText();
                String DienThoai = txtDienThoai.getText();
                String DiaChi = txtDiaChi.getText();
                String DoiTuong = txtDoiTuong.getText();
                DocGia DG1 = new DocGia(maDG,HoTen,NgaySinh,GioiTinh,DienThoai,DiaChi,DoiTuong);

            try {
                TheThuVienDAO.getInstance().delete(ttv);
                JOptionPane.showMessageDialog(null, "Xóa Thẻ Thư viện thành công");  
                showData();
                cleanUI();  
                DocGiaDAO.getInstance().delete(DG1);
            } catch (Exception e) {
                e.printStackTrace();  
            }
                  }
              }  
            } else if (result == JOptionPane.NO_OPTION) {
                cleanUI();
                btnDel.setEnabled(true);
                btnUp.setEnabled(true);
                JOptionPane.showMessageDialog(null, "Đã hủy xóa thẻ thư viện");
              }
            
                
            
        }
        
    }//GEN-LAST:event_btnDelActionPerformed

    private void btnUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpActionPerformed
        // TODO add your handling code here:
        if (btnUp.getText().equalsIgnoreCase("Sửa")) {
            if(tableTTV.getSelectedRowCount() != 1) {
              JOptionPane.showMessageDialog(null, "Vui lòng chọn hàng muốn sửa"); 
            }
            else {
            btnUp.setText("Hủy");
            btnDel.setEnabled(false);
            btnSave.setEnabled(true);
            inputMaThe.setEnabled(false);
            inputMaDG.setEnabled(false);
            inputNgayTao.setEnabled(true);
            inputHanThe.setEnabled(true);
            btnSave.setVisible(true); 
            }
        }
        else {
            cleanUI();
            btnUp.setText("Sửa");
            JOptionPane.showMessageDialog(null, "Hủy sửa Nhà Cung Cấp thành công"); 
        }
        
    }//GEN-LAST:event_btnUpActionPerformed

    private void menuMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMainActionPerformed
        // TODO add your handling code here:
        Main main = new Main();
        setVisible(false);
    }//GEN-LAST:event_menuMainActionPerformed

    private void menuDGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDGActionPerformed
        // TODO add your handling code here:
        QuanLyDG mainDG = new QuanLyDG();
        setVisible(false);
    }//GEN-LAST:event_menuDGActionPerformed

    private void menuTheDGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTheDGActionPerformed
        // TODO add your handling code here:
        QuanLyThe mainThe = new QuanLyThe();
        setVisible(false);
    }//GEN-LAST:event_menuTheDGActionPerformed

    private void menuQuanLyTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuQuanLyTTActionPerformed
        // TODO add your handling code here:
        QuanLyThuThu mainTT = new QuanLyThuThu();
        setVisible(false);
    }//GEN-LAST:event_menuQuanLyTTActionPerformed

    private void menuQuanLyDauSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuQuanLyDauSachActionPerformed
        // TODO add your handling code here:
        QuanLyDauSach mainQuanLyDauSach = new QuanLyDauSach();
        setVisible(false);
    }//GEN-LAST:event_menuQuanLyDauSachActionPerformed

    private void menuNhapSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNhapSachActionPerformed
        // TODO add your handling code here:
        QuanLyPhieuNhap mainLyPhieuNhap = new QuanLyPhieuNhap();
        setVisible(false);
    }//GEN-LAST:event_menuNhapSachActionPerformed

    private void menuThemPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuThemPNActionPerformed
        // TODO add your handling code here:
        QuanLyThemPN menQuanLyThemPN = new QuanLyThemPN();
        setVisible(false);
    }//GEN-LAST:event_menuThemPNActionPerformed

    private void menuNhaCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNhaCCActionPerformed
        // TODO add your handling code here:
        QuanLyNhaCungCap mainNCC = new QuanLyNhaCungCap();
        setVisible(false);
    }//GEN-LAST:event_menuNhaCCActionPerformed

    private void menuQuanLyMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuQuanLyMuonActionPerformed
        // TODO add your handling code here:
        QuanLyMuon mainMuon = new QuanLyMuon();
        setVisible(false);
    }//GEN-LAST:event_menuQuanLyMuonActionPerformed

    private void menuThemPhieuMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuThemPhieuMuonActionPerformed
        // TODO add your handling code here:
        QuanLyThemPM mainThemPM = new QuanLyThemPM();
        setVisible(false);
    }//GEN-LAST:event_menuThemPhieuMuonActionPerformed

    private void menuQuanLyPhieuTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuQuanLyPhieuTraActionPerformed
        // TODO add your handling code here:
        QuanLyPhieuTra mainQuanLyPhieuTra = new QuanLyPhieuTra();
        setVisible(false);
    }//GEN-LAST:event_menuQuanLyPhieuTraActionPerformed

    private void menuQuanLyThemPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuQuanLyThemPTActionPerformed
        // TODO add your handling code here:
        QuanLyThemPT mainThemPT = new QuanLyThemPT();
        setVisible(false);
    }//GEN-LAST:event_menuQuanLyThemPTActionPerformed

    private void menuThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuThongKeActionPerformed
        // TODO add your handling code here:
        ThongKe mainTk = new ThongKe();
        setVisible(false);
    }//GEN-LAST:event_menuThongKeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyThe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyThe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyThe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyThe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyThe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnTaoThe;
    private javax.swing.JButton btnUp;
    private javax.swing.JButton closeBTN;
    private javax.swing.JButton dgBTN;
    private com.toedter.calendar.JDateChooser inputHanThe;
    private javax.swing.JTextField inputMaDG;
    private javax.swing.JTextField inputMaThe;
    private com.toedter.calendar.JDateChooser inputNgayTao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JButton mainBTN;
    private javax.swing.JMenuItem menuDG;
    private javax.swing.JMenuItem menuMain;
    private javax.swing.JMenuItem menuNhaCC;
    private javax.swing.JMenuItem menuNhapSach;
    private javax.swing.JMenuItem menuQuanLyDauSach;
    private javax.swing.JMenuItem menuQuanLyMuon;
    private javax.swing.JMenuItem menuQuanLyPhieuTra;
    private javax.swing.JMenuItem menuQuanLyTT;
    private javax.swing.JMenuItem menuQuanLyThemPT;
    private javax.swing.JMenuItem menuTheDG;
    private javax.swing.JMenuItem menuThemPN;
    private javax.swing.JMenuItem menuThemPhieuMuon;
    private javax.swing.JMenuItem menuThongKe;
    private javax.swing.JTable tableDG;
    private javax.swing.JTable tableTTV;
    private java.awt.Label txtDiaChi;
    private java.awt.Label txtDienThoai;
    private java.awt.Label txtDoiTuong;
    private java.awt.Label txtGioiTinh;
    private javax.swing.JLabel txtHanThe;
    private java.awt.Label txtHoTen;
    private javax.swing.JLabel txtMaDG;
    private java.awt.Label txtMaDG1;
    private javax.swing.JLabel txtMaThe;
    private java.awt.Label txtNgaySinh;
    // End of variables declaration//GEN-END:variables
}
