/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import  model.*;
import database.ConnectionSQL;
import DAO.*;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javafx.scene.input.MouseEvent;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.MouseInputAdapter;
import javax.swing.table.TableModel;

/**
 *
 * @author minht
 */
public class QuanLyDG extends javax.swing.JFrame {
    public static  QuanLyDG mainQuanLyDG = null;
    Connection conn;
    List<DocGia> listDG = new ArrayList<>();
    DefaultTableModel tableModel = null;
    boolean check = false;
    
    public void showData(){
         listDG = DocGiaDAO.getInstance().selectAll();
         tableModel.setRowCount(0);
         listDG.forEach((DG) -> {
            tableModel.addRow(new Object[] {DG.getMaDG(), DG.getHoTenDG(), DG.getNgaySinhDG(),DG.getGioiTinhDG(),DG.getDienThoaiDG(),DG.getDiaChiDG(),DG.getDoiTuong()});
        });

    }
    

    
    public void cleanUI(){
        inputMa.setText("");
        inputTen.setText("");
        inputDC.setText("");
        inputDT.setText("");
        inputNS.setCalendar(null);
        inputMa.setEnabled(false);
        inputTen.setEnabled(false);
        inputDC.setEnabled(false);
        inputDT.setEnabled(false);
        inputNS.setEnabled(false);
        btnNam.setEnabled(false);
        btnNu.setEnabled(false);
        listDT.setEnabled(false);
        btnSave.setVisible(false);
        btnAdd.setText("Thêm");
        btnDel.setEnabled(true);
        btnUp.setEnabled(true);
        btnAdd.setEnabled(true);
       
    }
    
    public void defUI(){
        inputMa.setText("");
        inputTen.setText("");
        inputDC.setText("");
        inputDT.setText("");
        inputTen.setEnabled(true);
        inputDC.setEnabled(true);
        inputDT.setEnabled(true);
        inputNS.setEnabled(true);
        btnNam.setEnabled(true);
        btnNu.setEnabled(true);
        listDT.setEnabled(true);
        inputMa.requestFocus(); 
        listDT.setSelectedIndex(0);
    }
    
    /**
     * Creates new form QuanLyDG
     */
    public QuanLyDG() {
        initComponents();
        setTitle("Quản lý độc giả");
        setVisible(true);
        setSize(1020, 840);
        setResizable(false);
        //set vị trí from ở trung tâm
        setLocationRelativeTo(null);

        
        
        listDT.addItem("");
        listDT.addItem("Sinh viên"); 
        listDT.addItem("Giảng viên");
        listDT.addItem("Nhân viên");
        try {
            conn = ConnectionSQL.getConnection();
        } catch (Exception e) {
            e.printStackTrace();
        }

        tableModel = (DefaultTableModel) table.getModel();
        table.setDefaultEditor(Object.class, null); // ngăn ko cho chỉnh sửa trên bảng ghi
        showData();
        cleanUI();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        inputDC = new javax.swing.JTextField();
        inputDT = new javax.swing.JTextField();
        inputMa = new javax.swing.JTextField();
        inputTen = new javax.swing.JTextField();
        btnNam = new javax.swing.JRadioButton();
        btnNu = new javax.swing.JRadioButton();
        inputNS = new com.toedter.calendar.JDateChooser();
        listDT = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnUp = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        backHome = new javax.swing.JButton();
        closeBTN = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        mainQLTheBTn = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuMain = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem8 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuDG = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        menuTheDG = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuQuanLyTT = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuQuanLyDauSach = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menuNhapSach = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        menuThemPN = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        menuNhaCC = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        menuQuanLyMuon = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        menuThemPhieuMuon = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuQuanLyPhieuTra = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        menuQuanLyThemPT = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        menuThongKe = new javax.swing.JMenuItem();

        jPanel4.setBackground(new java.awt.Color(27, 70, 139));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jMenuItem1.setText("jMenuItem1");

        jMenu6.setText("jMenu6");

        jMenuItem10.setText("jMenuItem10");

        jMenuItem11.setText("jMenuItem11");

        jMenuItem12.setText("jMenuItem12");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(242, 248, 249));
        setPreferredSize(new java.awt.Dimension(1020, 755));

        jPanel1.setBackground(new java.awt.Color(245, 245, 245));

        jLabel1.setBackground(new java.awt.Color(27, 70, 139));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(27, 70, 139));
        jLabel1.setText("QUẢN LÝ ĐỘC GIẢ");

        jPanel3.setBackground(new java.awt.Color(245, 245, 245));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true), "Thông tin chi tiết", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel2.setText("Mã DG :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel3.setText("Họ Tên :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel4.setText("Ngày Sinh :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel5.setText("Địa Chỉ  :");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel6.setText("Đối Tượng  :");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel7.setText("Điện Thoại   :");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Giới Tính :");

        inputDC.setPreferredSize(new java.awt.Dimension(280, 22));

        inputDT.setPreferredSize(new java.awt.Dimension(280, 22));

        inputTen.setPreferredSize(new java.awt.Dimension(280, 22));

        buttonGroup1.add(btnNam);
        btnNam.setText("Nam");

        buttonGroup1.add(btnNu);
        btnNu.setText("Nữ");

        inputNS.setDateFormatString("dd-MM-yyyy");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnNam)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNu))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(inputMa)
                            .addComponent(inputTen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inputNS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(102, 102, 102)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(inputDC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(listDT, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(32, 32, 32)
                                .addComponent(inputDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(inputMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(inputDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(inputDC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(inputTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(inputNS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(btnNam)
                            .addComponent(btnNu)))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(listDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(245, 245, 245));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "Danh sách độc giả", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        table.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã DG", "Họ Tên", "Ngày Sinh", "Giới Tính", "Điện Thoại", "Địa chỉ", "Đối tượng"
            }
        ));
        table.setFocusTraversalPolicyProvider(true);
        table.setRequestFocusEnabled(false);
        table.setRowHeight(30);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 966, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnAdd.setText("Thêm");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUp.setText("Sửa");
        btnUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpActionPerformed(evt);
            }
        });

        btnDel.setText("Xóa");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        backHome.setText("Về Trang Chủ");
        backHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backHomeActionPerformed(evt);
            }
        });

        closeBTN.setText("Thoát");
        closeBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBTNActionPerformed(evt);
            }
        });

        btnSave.setText("Lưu");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        mainQLTheBTn.setText("Quản lý thẻ thư viện");
        mainQLTheBTn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainQLTheBTnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnUp, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnDel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(backHome, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(mainQLTheBTn)
                                .addGap(16, 16, 16)
                                .addComponent(closeBTN)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnUp)
                    .addComponent(btnDel)
                    .addComponent(btnSave))
                .addGap(10, 10, 10)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainQLTheBTn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(closeBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(backHome, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );

        jPanel5.setBackground(new java.awt.Color(27, 70, 139));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(252, 252, 255));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(27, 70, 139));
        jLabel10.setText("TRƯỜNG ĐẠI HỌC TÀI CHÍNH MARKETING");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(27, 70, 139));
        jLabel11.setText("THƯ VIỆN");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(0, 630, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thuvien/img/miniLogo.jpg"))); // NOI18N

        jPanel6.setBackground(new java.awt.Color(27, 70, 139));
        jPanel6.setPreferredSize(new java.awt.Dimension(0, 20));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(204, 204, 204));
        jMenuBar1.setOpaque(true);

        jMenu1.setText("Tiện ích");
        jMenu1.setMargin(new java.awt.Insets(3, 12, 3, 12));

        menuMain.setText("Trang chủ");
        menuMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMainActionPerformed(evt);
            }
        });
        jMenu1.add(menuMain);
        jMenu1.add(jSeparator2);

        jMenuItem8.setText("Giới thiệu");
        jMenu1.add(jMenuItem8);
        jMenu1.add(jSeparator3);

        jMenuItem9.setText("Thông tin liên hệ");
        jMenu1.add(jMenuItem9);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Quản lý độc giả");
        jMenu2.setMargin(new java.awt.Insets(3, 12, 3, 12));

        menuDG.setText("Danh sách độc giả");
        menuDG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDGActionPerformed(evt);
            }
        });
        jMenu2.add(menuDG);
        jMenu2.add(jSeparator4);

        menuTheDG.setText("Danh sách thẻ độc giả");
        menuTheDG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTheDGActionPerformed(evt);
            }
        });
        jMenu2.add(menuTheDG);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Quản lý thu thư");
        jMenu3.setMargin(new java.awt.Insets(3, 12, 3, 12));

        menuQuanLyTT.setText("Danh mục thủ thư");
        menuQuanLyTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuQuanLyTTActionPerformed(evt);
            }
        });
        jMenu3.add(menuQuanLyTT);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Quản lý sách");
        jMenu4.setMargin(new java.awt.Insets(3, 12, 3, 12));

        menuQuanLyDauSach.setText("Danh mục đầu sách");
        menuQuanLyDauSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuQuanLyDauSachActionPerformed(evt);
            }
        });
        jMenu4.add(menuQuanLyDauSach);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Quản lý nhập sách");
        jMenu5.setMargin(new java.awt.Insets(3, 12, 3, 12));

        menuNhapSach.setText("Danh mục nhập sách");
        menuNhapSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNhapSachActionPerformed(evt);
            }
        });
        jMenu5.add(menuNhapSach);
        jMenu5.add(jSeparator6);

        menuThemPN.setText("Thêm Phiếu nhập");
        menuThemPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuThemPNActionPerformed(evt);
            }
        });
        jMenu5.add(menuThemPN);
        jMenu5.add(jSeparator5);

        menuNhaCC.setText("Danh mục nhà cung cấp");
        menuNhaCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNhaCCActionPerformed(evt);
            }
        });
        jMenu5.add(menuNhaCC);

        jMenuBar1.add(jMenu5);

        jMenu7.setText("Quản lý mượn - trả");
        jMenu7.setMargin(new java.awt.Insets(3, 12, 3, 12));

        menuQuanLyMuon.setText("Danh sách mượn");
        menuQuanLyMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuQuanLyMuonActionPerformed(evt);
            }
        });
        jMenu7.add(menuQuanLyMuon);
        jMenu7.add(jSeparator7);

        menuThemPhieuMuon.setText("Thêm phiếu mượn");
        menuThemPhieuMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuThemPhieuMuonActionPerformed(evt);
            }
        });
        jMenu7.add(menuThemPhieuMuon);
        jMenu7.add(jSeparator1);

        menuQuanLyPhieuTra.setText("Danh sách trả");
        menuQuanLyPhieuTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuQuanLyPhieuTraActionPerformed(evt);
            }
        });
        jMenu7.add(menuQuanLyPhieuTra);
        jMenu7.add(jSeparator8);

        menuQuanLyThemPT.setText("Thêm phiếu trả");
        menuQuanLyThemPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuQuanLyThemPTActionPerformed(evt);
            }
        });
        jMenu7.add(menuQuanLyThemPT);

        jMenuBar1.add(jMenu7);

        jMenu8.setText("Tổng thống kê");
        jMenu8.setMargin(new java.awt.Insets(3, 12, 3, 12));

        menuThongKe.setText("Thống kê");
        menuThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuThongKeActionPerformed(evt);
            }
        });
        jMenu8.add(menuThongKe);

        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(0, 0, 0)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 1020, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:

        
        String tblMaDG = tableModel.getValueAt(table.getSelectedRow(), 0).toString();
        String tblHoTenDG = tableModel.getValueAt(table.getSelectedRow(), 1).toString();
        String tblNgaySinhDG = tableModel.getValueAt(table.getSelectedRow(), 2).toString();
        String tblGioiTinhDG = tableModel.getValueAt(table.getSelectedRow(), 3).toString();
        String tblDiaChiDG = tableModel.getValueAt(table.getSelectedRow(), 5).toString();
        String tblDienThoaiDG = tableModel.getValueAt(table.getSelectedRow(), 4).toString();
        String tblDoiTuongDG = tableModel.getValueAt(table.getSelectedRow(), 6).toString();

        inputMa.setText(tblMaDG);
        inputTen.setText(tblHoTenDG); 
       
        try {
          Date d = new SimpleDateFormat("yyyy-MM-dd").parse(tblNgaySinhDG);
            inputNS.setDate(d);  
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        if (tblGioiTinhDG.equalsIgnoreCase("Nam")) {
            btnNam.setSelected(true);
        } else {
            btnNu.setSelected(true);
        }
        inputDT.setText(tblDienThoaiDG);
        inputDC.setText(tblDiaChiDG);
        if (tblDoiTuongDG.equalsIgnoreCase("Sinh viên")) {
            listDT.setSelectedIndex(1);
        } else {
            listDT.setSelectedIndex(2);
        }
    }//GEN-LAST:event_tableMouseClicked

    private void closeBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBTNActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        
    }//GEN-LAST:event_closeBTNActionPerformed

    private void backHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backHomeActionPerformed
        // TODO add your handling code here:
        Main main = new Main();
        main.setVisible(true);
        main.CLock();
        main.CurrentDate();
        setVisible(false);
    }//GEN-LAST:event_backHomeActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        
        if(btnAdd.getText().equalsIgnoreCase("Thêm")) {
        defUI();
        btnAdd.setText("Hủy");
        btnDel.setEnabled(false);
        btnUp.setEnabled(false);
        btnSave.setVisible(true);
        check = true;
        } else {
            cleanUI();
            btnDel.setEnabled(true);
            btnUp.setEnabled(true);
            JOptionPane.showMessageDialog(null, "Hủy thêm độc giả thành công");
        }
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        if(check) {
//                inputMa.setEnabled(true);
                String msDG = "";
                String splitMaDG ="";
                int newMaDGInt;
                String newMaDGString ="";
                ArrayList<DocGia> listNewMaDG = DocGiaDAO.getInstance().selectNewMaDG();
                for (DocGia docGia : listNewMaDG) {
                    msDG = docGia.getMaDG();
                }
                splitMaDG = msDG.substring(2);
                newMaDGInt = Integer.valueOf(splitMaDG) +1;
                if (newMaDGInt > 10) {
                   newMaDGString = "DG0" + Integer.toString(newMaDGInt);
                } else if (newMaDGInt > 100) {
                   newMaDGString = "DG" + Integer.toString(newMaDGInt);
                }
                String HoTen = inputTen.getText();
                Date date = inputNS.getDate();  
                String NgaySinh = DateFormat.getDateInstance().format(date);
                String GioiTinh = "";
                if(btnNam.isSelected()) {
                    GioiTinh = "Nam";
                } else {
                    GioiTinh = "Nữ";
                }
                String DienThoai = inputDT.getText();
                String DiaChi = inputDC.getText();
                String DoiTuong = "";
                if (listDT.getSelectedIndex() == 1) {
                    DoiTuong = "Sinh viên";
                } else if (listDT.getSelectedIndex() == 2) {
                    DoiTuong = "Giảng viên";
                }
                DocGia DG1 = new DocGia(newMaDGString,HoTen,NgaySinh,GioiTinh,DienThoai,DiaChi,DoiTuong);
                
            try {
                DocGiaDAO.getInstance().insert(DG1);
                JOptionPane.showMessageDialog(null, "Thêm Độc Giả thành công");
                showData(); 
                btnAdd.setText("Thêm");
                cleanUI();
            } catch (Exception e) {
                    e.printStackTrace();
                 }
              
           
        }
        
        else {
                String msDG = inputMa.getText();
                String HoTen = inputTen.getText();
                Date date = inputNS.getDate();  
                String NgaySinh = DateFormat.getDateInstance().format(date);
                String GioiTinh = "";
                if(btnNam.isSelected()) {
                    GioiTinh = "Nam";
                } else {
                    GioiTinh = "Nữ";
                }
                String DienThoai = inputDT.getText();
                String DiaChi = inputDC.getText();
                String DoiTuong = "";
                if (listDT.getSelectedIndex() == 1) {
                    DoiTuong = "Sinh viên";
                } else if (listDT.getSelectedIndex() == 2) {
                    DoiTuong = "Giảng viên";
                }
                DocGia DG1 = new DocGia(msDG,HoTen,NgaySinh,GioiTinh,DienThoai,DiaChi,DoiTuong);
            
            try {
                DocGiaDAO.getInstance().update(DG1);
                JOptionPane.showMessageDialog(null, "Sửa Độc Giả thành công");  
                showData();
                btnUp.setText("Sửa");     
                cleanUI();
                
            } catch (Exception ex) {
               ex.printStackTrace();

            }
        }   
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        // TODO add your handling code here:
        if(table.getSelectedRowCount() != 1) {
          JOptionPane.showMessageDialog(null, "Vui lòng chọn hàng muốn Xóa"); 
        }
        else {
                String msDG = inputMa.getText();
                String HoTen = inputTen.getText();
                Calendar date = inputNS.getCalendar();
                SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                String NgaySinh = dateFormat.format(date.getTime());
                String GioiTinh = "";
                if(btnNam.isSelected()) {
                    GioiTinh = "Nam";
                } else {
                    GioiTinh = "Nữ";
                }
                String DienThoai = inputDT.getText();
                String DiaChi = inputDC.getText();
                String DoiTuong = "";
                if (listDT.getSelectedIndex() == 1) {
                    DoiTuong = "Sinh viên";
                } else if (listDT.getSelectedIndex() == 2) {
                    DoiTuong = "Giảng viên";
                }
                DocGia DG1 = new DocGia(msDG,HoTen,NgaySinh,GioiTinh,DienThoai,DiaChi,DoiTuong);
            try {
                DocGiaDAO.getInstance().delete(DG1);
                JOptionPane.showMessageDialog(null, "Xóa Độc giả thành công");  
                showData();
                cleanUI();  
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        
    }//GEN-LAST:event_btnDelActionPerformed

    private void btnUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpActionPerformed
        // TODO add your handling code here:
        if (btnUp.getText().equalsIgnoreCase("Sửa")) {
            if(table.getSelectedRowCount() != 1) {
              JOptionPane.showMessageDialog(null, "Vui lòng chọn hàng muốn sửa"); 
            }
            else {
            btnUp.setText("Hủy");
            btnAdd.setEnabled(false);
            btnDel.setEnabled(false);
            btnSave.setEnabled(true);
            inputMa.setEnabled(false);
            inputTen.setEnabled(true);
            inputDC.setEnabled(true);
            inputDT.setEnabled(true);
            inputNS.setEnabled(true);
            btnNam.setEnabled(true);
            btnNu.setEnabled(true);
            listDT.setEnabled(true);
            btnSave.setVisible(true);
            check = false;  
            }
        }
        else {
            cleanUI();
            btnUp.setText("Sửa");
            JOptionPane.showMessageDialog(null, "Hủy sửa Độc giả thành công"); 
        }
        
        
    }//GEN-LAST:event_btnUpActionPerformed

    private void mainQLTheBTnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainQLTheBTnActionPerformed
        // TODO add your handling code here:
        QuanLyThe mainQLThe = new QuanLyThe();
        setVisible(false);
    }//GEN-LAST:event_mainQLTheBTnActionPerformed

    private void menuMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMainActionPerformed
        // TODO add your handling code here:
        Main main = new Main();
        setVisible(false);
    }//GEN-LAST:event_menuMainActionPerformed

    private void menuDGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDGActionPerformed
        // TODO add your handling code here:
        QuanLyDG mainDG = new QuanLyDG();
        setVisible(false);
    }//GEN-LAST:event_menuDGActionPerformed

    private void menuTheDGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTheDGActionPerformed
        // TODO add your handling code here:
        QuanLyThe mainThe = new QuanLyThe();
        setVisible(false);
    }//GEN-LAST:event_menuTheDGActionPerformed

    private void menuNhapSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNhapSachActionPerformed
        // TODO add your handling code here:
        QuanLyPhieuNhap mainLyPhieuNhap = new QuanLyPhieuNhap();
        setVisible(false);
    }//GEN-LAST:event_menuNhapSachActionPerformed

    private void menuNhaCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNhaCCActionPerformed
        // TODO add your handling code here:
        QuanLyNhaCungCap mainNCC = new QuanLyNhaCungCap();
        setVisible(false);
    }//GEN-LAST:event_menuNhaCCActionPerformed

    private void menuQuanLyTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuQuanLyTTActionPerformed
        // TODO add your handling code here:
        QuanLyThuThu mainTT = new QuanLyThuThu();
        setVisible(false);
    }//GEN-LAST:event_menuQuanLyTTActionPerformed

    private void menuThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuThongKeActionPerformed
        // TODO add your handling code here:
        ThongKe mainTk = new ThongKe();
        setVisible(false);
    }//GEN-LAST:event_menuThongKeActionPerformed

    private void menuQuanLyMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuQuanLyMuonActionPerformed
        // TODO add your handling code here:
        QuanLyMuon mainMuon = new QuanLyMuon();
        setVisible(false);
    }//GEN-LAST:event_menuQuanLyMuonActionPerformed

    private void menuThemPhieuMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuThemPhieuMuonActionPerformed
        // TODO add your handling code here:
        QuanLyThemPM mainThemPM = new QuanLyThemPM();
        setVisible(false);
    }//GEN-LAST:event_menuThemPhieuMuonActionPerformed

    private void menuQuanLyPhieuTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuQuanLyPhieuTraActionPerformed
        // TODO add your handling code here:
        QuanLyPhieuTra mainQuanLyPhieuTra = new QuanLyPhieuTra();
        setVisible(false);
    }//GEN-LAST:event_menuQuanLyPhieuTraActionPerformed

    private void menuQuanLyThemPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuQuanLyThemPTActionPerformed
        // TODO add your handling code here:
        QuanLyThemPT mainThemPT = new QuanLyThemPT();
        setVisible(false);
    }//GEN-LAST:event_menuQuanLyThemPTActionPerformed

    private void menuQuanLyDauSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuQuanLyDauSachActionPerformed
        // TODO add your handling code here:
        QuanLyDauSach mainQuanLyDauSach = new QuanLyDauSach();
        setVisible(false);
    }//GEN-LAST:event_menuQuanLyDauSachActionPerformed

    private void menuThemPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuThemPNActionPerformed
        // TODO add your handling code here:
        QuanLyThemPN menQuanLyThemPN = new QuanLyThemPN();
        setVisible(false);
    }//GEN-LAST:event_menuThemPNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyDG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyDG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyDG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyDG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                mainQuanLyDG = new QuanLyDG();

//               mainQuanLyDG.setResizable(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backHome;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDel;
    private javax.swing.JRadioButton btnNam;
    private javax.swing.JRadioButton btnNu;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUp;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton closeBTN;
    private javax.swing.JTextField inputDC;
    private javax.swing.JTextField inputDT;
    private javax.swing.JTextField inputMa;
    private com.toedter.calendar.JDateChooser inputNS;
    private javax.swing.JTextField inputTen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JComboBox<String> listDT;
    private javax.swing.JButton mainQLTheBTn;
    private javax.swing.JMenuItem menuDG;
    private javax.swing.JMenuItem menuMain;
    private javax.swing.JMenuItem menuNhaCC;
    private javax.swing.JMenuItem menuNhapSach;
    private javax.swing.JMenuItem menuQuanLyDauSach;
    private javax.swing.JMenuItem menuQuanLyMuon;
    private javax.swing.JMenuItem menuQuanLyPhieuTra;
    private javax.swing.JMenuItem menuQuanLyTT;
    private javax.swing.JMenuItem menuQuanLyThemPT;
    private javax.swing.JMenuItem menuTheDG;
    private javax.swing.JMenuItem menuThemPN;
    private javax.swing.JMenuItem menuThemPhieuMuon;
    private javax.swing.JMenuItem menuThongKe;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
